# Part 1: CGMacros Cleaning

### Step 1: Load the Raw Files

In [1]:
import pandas as pd
from pathlib import Path

folder = Path(
    r"C:\Users\karth\Downloads\CGMacros_Datathon_Aug_2026\Datathon_Aug_2026"
)

cg_files = sorted(folder.glob("CGMacros-*.csv"))
bio_file = folder / "bio.csv"

print("Number of CGMacros files:", len(cg_files))
print("Bio file exists:", bio_file.exists())
print("First few files:", cg_files[:5])

Number of CGMacros files: 45
Bio file exists: True
First few files: [WindowsPath('C:/Users/karth/Downloads/CGMacros_Datathon_Aug_2026/Datathon_Aug_2026/CGMacros-001.csv'), WindowsPath('C:/Users/karth/Downloads/CGMacros_Datathon_Aug_2026/Datathon_Aug_2026/CGMacros-002.csv'), WindowsPath('C:/Users/karth/Downloads/CGMacros_Datathon_Aug_2026/Datathon_Aug_2026/CGMacros-003.csv'), WindowsPath('C:/Users/karth/Downloads/CGMacros_Datathon_Aug_2026/Datathon_Aug_2026/CGMacros-004.csv'), WindowsPath('C:/Users/karth/Downloads/CGMacros_Datathon_Aug_2026/Datathon_Aug_2026/CGMacros-005.csv')]

### Step 2: Check Number of Rows and Columns

In [2]:
# Read bio.csv
bio = pd.read_csv(bio_file)

# Read one CGMacros file as a sample
sample_cg = pd.read_csv(cg_files[0])

print("Bio shape:", bio.shape)
print("Bio columns:")
print(bio.columns.tolist())

print("\nSample CGMacros shape:", sample_cg.shape)
print("Sample CGMacros columns:")
print(sample_cg.columns.tolist())

Bio shape: (45, 24)
Bio columns:
['subject', 'Age', 'Gender', 'BMI', 'Body weight ', 'Height ', 'Self-identify ', 'A1c PDL (Lab)', 'Fasting GLU - PDL (Lab)', 'Insulin ', 'Triglycerides', 'Cholesterol', 'HDL', 'Non HDL ', 'LDL (Cal)', 'VLDL (Cal)', 'Cho/HDL Ratio', 'Collection time PDL (Lab)', '#1 Contour Fingerstick GLU', 'Time (t)', ' #2 Contour Fingerstick GLU', 'Time (t).1', '#3 Contour Fingerstick GLU', 'Time (t).2']

Sample CGMacros shape: (14730, 15)
Sample CGMacros columns:
['Unnamed: 0', 'Timestamp', 'Libre GL', 'Dexcom GL', 'HR', 'Calories (Activity)', 'METs', 'Meal Type', 'Calories', 'Carbs', 'Protein', 'Fat', 'Fiber', 'Amount Consumed ', 'Image path']

### Step 3: Check Whether All 45 CGMacros Files Have the Same Columns

In [3]:
# Check the column structure of every CGMacros file

column_check = {}

for file in cg_files:
    df = pd.read_csv(file, nrows=0)
    column_check[file.name] = df.columns.tolist()

# Use the first file's columns as the expected structure
expected_columns = column_check[cg_files[0].name]

different_files = []

for filename, columns in column_check.items():
    if columns != expected_columns:
        different_files.append(filename)

print("Total CGMacros files checked:", len(column_check))
print("Files with different columns:", different_files)

Total CGMacros files checked: 45
Files with different columns: ['CGMacros-002.csv', 'CGMacros-003.csv', 'CGMacros-004.csv', 'CGMacros-005.csv', 'CGMacros-006.csv', 'CGMacros-007.csv', 'CGMacros-008.csv', 'CGMacros-009.csv', 'CGMacros-010.csv', 'CGMacros-011.csv', 'CGMacros-012.csv', 'CGMacros-013.csv', 'CGMacros-014.csv', 'CGMacros-015.csv', 'CGMacros-016.csv', 'CGMacros-017.csv', 'CGMacros-018.csv', 'CGMacros-019.csv', 'CGMacros-020.csv', 'CGMacros-021.csv', 'CGMacros-022.csv', 'CGMacros-023.csv', 'CGMacros-026.csv', 'CGMacros-027.csv', 'CGMacros-028.csv', 'CGMacros-029.csv', 'CGMacros-030.csv', 'CGMacros-031.csv', 'CGMacros-032.csv', 'CGMacros-033.csv', 'CGMacros-034.csv', 'CGMacros-035.csv', 'CGMacros-036.csv', 'CGMacros-038.csv', 'CGMacros-039.csv', 'CGMacros-041.csv', 'CGMacros-042.csv', 'CGMacros-043.csv', 'CGMacros-044.csv', 'CGMacros-045.csv', 'CGMacros-046.csv', 'CGMacros-047.csv', 'CGMacros-048.csv', 'CGMacros-049.csv']

### Step 4: Identify Column Differences Before Combining Files

In [4]:
# Compare every file's columns with CGMacros-001.csv

first_file = cg_files[0]
first_columns = pd.read_csv(first_file, nrows=0).columns.tolist()

print("Reference file:", first_file.name)
print("Reference columns:")
print(first_columns)

for file in cg_files[1:]:
    columns = pd.read_csv(file, nrows=0).columns.tolist()

    if columns != first_columns:
        missing = [col for col in first_columns if col not in columns]
        extra = [col for col in columns if col not in first_columns]

        print("\nFile:", file.name)
        print("Missing compared with first file:", missing)
        print("Extra compared with first file:", extra)

Reference file: CGMacros-001.csv
Reference columns:
['Unnamed: 0', 'Timestamp', 'Libre GL', 'Dexcom GL', 'HR', 'Calories (Activity)', 'METs', 'Meal Type', 'Calories', 'Carbs', 'Protein', 'Fat', 'Fiber', 'Amount Consumed ', 'Image path']

File: CGMacros-002.csv
Missing compared with first file: ['Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-003.csv
Missing compared with first file: ['Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-004.csv
Missing compared with first file: ['Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-005.csv
Missing compared with first file: ['Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-006.csv
Missing compared with first file: ['Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-007.csv
Missing compared with first file: ['Unnamed: 0', 'Calories (Activity)', 'Amount Consumed ']
Extra compared with first file: ['Steps', 'RecordIndex', 'Amount Consumed']

File: CGMacros-008.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-009.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-010.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-011.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-012.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-013.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Sugar', 'Amount Consumed']

File: CGMacros-014.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-015.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-016.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-017.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-018.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-019.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-020.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-021.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-022.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-023.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-026.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-027.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-028.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: []

File: CGMacros-029.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: []

File: CGMacros-030.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-031.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-032.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-033.csv
Missing compared with first file: ['METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-034.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-035.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-036.csv
Missing compared with first file: ['Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-038.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-039.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-041.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-042.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-043.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-044.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-045.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-046.csv
Missing compared with first file: ['Unnamed: 0', 'METs', 'Amount Consumed ']
Extra compared with first file: ['Intensity', 'Amount Consumed']

File: CGMacros-047.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-048.csv
Missing compared with first file: ['Unnamed: 0', 'Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

File: CGMacros-049.csv
Missing compared with first file: ['Amount Consumed ']
Extra compared with first file: ['Amount Consumed']

### Step 5: Prepare Files Before Combining

In [5]:
# Read and standardize every CGMacros file

cleaned_frames = []

for file in cg_files:
    df = pd.read_csv(file)

    # Remove spaces before and after column names
    df.columns = df.columns.str.strip()

    # Remove unnecessary saved-index columns
    df = df.loc[:, ~df.columns.str.startswith("Unnamed")]

    # Extract subject number from the filename
    subject_id = int(file.stem.split("-")[-1])
    df.insert(0, "subject", subject_id)

    # Keep the source filename for validation
    df.insert(1, "source_file", file.name)

    cleaned_frames.append(df)

print("Files prepared:", len(cleaned_frames))
print("First file shape after preparation:", cleaned_frames[0].shape)
print("First file columns:")
print(cleaned_frames[0].columns.tolist())

Files prepared: 45
First file shape after preparation: (14730, 16)
First file columns:
['subject', 'source_file', 'Timestamp', 'Libre GL', 'Dexcom GL', 'HR', 'Calories (Activity)', 'METs', 'Meal Type', 'Calories', 'Carbs', 'Protein', 'Fat', 'Fiber', 'Amount Consumed', 'Image path']

### Step 6: Combine All 45 CGMacros Files

In [6]:
combined_cg = pd.concat(cleaned_frames, ignore_index=True, sort=False)

print("Combined shape:", combined_cg.shape)
print("Number of subjects:", combined_cg["subject"].nunique())
print("Columns:")
print(combined_cg.columns.tolist())

combined_cg.head()

Combined shape: (687580, 20)
Number of subjects: 45
Columns:
['subject', 'source_file', 'Timestamp', 'Libre GL', 'Dexcom GL', 'HR', 'Calories (Activity)', 'METs', 'Meal Type', 'Calories', 'Carbs', 'Protein', 'Fat', 'Fiber', 'Amount Consumed', 'Image path', 'Steps', 'RecordIndex', 'Intensity', 'Sugar']

,subject,source_file,Timestamp,Libre GL,Dexcom GL,HR,Calories (Activity),METs,Meal Type,Calories,Carbs,Protein,Fat,Fiber,Amount Consumed,Image path,Steps,RecordIndex,Intensity,Sugar
0,1,CGMacros-001.csv,5/1/2020 10:30,84.000000,NaN,56.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,CGMacros-001.csv,5/1/2020 10:31,84.133333,NaN,56.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,CGMacros-001.csv,5/1/2020 10:32,84.266667,NaN,57.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,CGMacros-001.csv,5/1/2020 10:33,84.400000,NaN,54.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,CGMacros-001.csv,5/1/2020 10:34,84.533333,NaN,55.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 7: Check Missing Values

In [7]:
# Count standard missing values
print(combined_cg.isna().sum())

# Count cells containing only spaces in text columns
blank_spaces = combined_cg.select_dtypes(include="object").apply(
    lambda col: col.astype("string").str.strip().eq("").sum()
)

print("\nBlank-space values:")
print(blank_spaces)

subject                     0
source_file                 0
Timestamp                   0
Libre GL                  220
Dexcom GL               57755
HR                      77324
Calories (Activity)     35446
METs                   186502
Meal Type              685874
Calories               685874
Carbs                  685874
Protein                685874
Fat                    685874
Fiber                  685875
Amount Consumed        685938
Image path             684383
Steps                  681925
RecordIndex            687563
Intensity              530870
Sugar                  687541
dtype: int64

Blank-space values:
source_file    0
Timestamp      0
Meal Type      0
Image path     0
dtype: int32

### Step 8: Check and Correct Data Types

In [8]:
combined_cg.dtypes

subject                  int64
source_file             object
Timestamp               object
Libre GL               float64
Dexcom GL              float64
HR                     float64
Calories (Activity)    float64
METs                   float64
Meal Type               object
Calories               float64
Carbs                  float64
Protein                float64
Fat                    float64
Fiber                  float64
Amount Consumed        float64
Image path              object
Steps                  float64
RecordIndex            float64
Intensity              float64
Sugar                  float64
dtype: object

In [9]:
print("HR:", combined_cg["HR"].dropna().mod(1).eq(0).all())
print("Steps:", combined_cg["Steps"].dropna().mod(1).eq(0).all())
print("Intensity:", combined_cg["Intensity"].dropna().mod(1).eq(0).all())

HR: True
Steps: True
Intensity: True

In [10]:
combined_cg["HR"] = combined_cg["HR"].astype("Int64")
combined_cg["Steps"] = combined_cg["Steps"].astype("Int64")
combined_cg["Intensity"] = combined_cg["Intensity"].astype("Int64")

In [11]:
combined_cg[["HR", "Steps", "Intensity"]].dtypes

HR           Int64
Steps        Int64
Intensity    Int64
dtype: object

### Step 9: Convert and Validate Timestamp

In [12]:
# Restore original combined data
combined_cg = pd.concat(
    cleaned_frames,
    ignore_index=True,
    sort=False
)

# Keep original timestamp text as a backup
combined_cg["Timestamp_original"] = combined_cg["Timestamp"]

# Convert different timestamp formats
combined_cg["Timestamp"] = pd.to_datetime(
    combined_cg["Timestamp_original"],
    format="mixed",
    errors="coerce"
)

print("Total rows:", len(combined_cg))
print("Successfully converted:", combined_cg["Timestamp"].notna().sum())
print("Failed timestamps:", combined_cg["Timestamp"].isna().sum())

Total rows: 687580
Successfully converted: 687580
Failed timestamps: 0

### Step 10: Check Duplicate Subject–Timestamp Records

In [13]:
# Check repeated subject and timestamp combinations
duplicate_subject_time = combined_cg.duplicated(
    subset=["subject", "Timestamp"],
    keep=False
)

print(
    "Rows with repeated subject and timestamp:",
    duplicate_subject_time.sum()
)

combined_cg.loc[
    duplicate_subject_time
].sort_values(
    ["subject", "Timestamp"]
).head(20)

Rows with repeated subject and timestamp: 0

Empty DataFrame
Columns: [subject, source_file, Timestamp, Libre GL, Dexcom GL, HR, Calories (Activity), METs, Meal Type, Calories, Carbs, Protein, Fat, Fiber, Amount Consumed, Image path, Steps, RecordIndex, Intensity, Sugar, Timestamp_original]
Index: []

[0 rows x 21 columns]

#### Step 10.1: Check Fully Duplicate Rows

In [14]:
exact_duplicate_count = combined_cg.duplicated().sum()

print("Completely identical duplicate rows:", exact_duplicate_count)

Completely identical duplicate rows: 0

### Step 11: Check Numeric Columns Against Documented Ranges

In [15]:
numeric_columns = [
    "Libre GL",
    "Dexcom GL",
    "HR",
    "Calories (Activity)",
    "METs",
    "Calories",
    "Carbs",
    "Protein",
    "Fat",
    "Fiber",
    "Amount Consumed",
    "Steps",
    "RecordIndex",
    "Intensity",
    "Sugar"
]

numeric_summary = combined_cg[numeric_columns].describe().T

numeric_summary[
    ["count", "mean", "std", "min", "25%", "50%", "75%", "max"]
]

,count,mean,std,min,25%,50%,75%,max
Libre GL,687360.0,109.055937,41.279751,40.0,83.4000,100.20000,125.00000,405.0000
Dexcom GL,629825.0,140.873351,42.026542,40.0,113.0000,130.80000,157.20000,400.0000
HR,610256.0,78.830738,15.294763,30.0,68.0000,79.00000,88.00000,176.0000
Calories (Activity),652134.0,1.835609,1.464122,0.0,1.0114,1.17821,1.87185,16.1784
METs,501078.0,17.212576,13.142785,0.0,10.0000,11.00000,15.00000,132.0000
Calories,1706.0,505.858968,329.540743,0.0,268.0000,448.00000,712.00000,2826.0000
Carbs,1706.0,52.080715,40.066376,0.0,24.0000,50.00000,73.00000,761.0000
Protein,1706.0,29.247421,25.662044,0.0,10.0000,22.00000,44.00000,148.0000
Fat,1706.0,19.783763,20.752374,0.0,10.0000,14.00000,30.00000,508.0000
Fiber,1705.0,17.897243,143.671402,0.0,0.0000,4.00000,7.00000,2830.0000
Amount Consumed,1642.0,97.865865,91.665339,0.0,100.0000,100.00000,100.00000,900.0000
Steps,5655.0,8.160743,22.200962,0.0,0.0000,0.00000,0.00000,116.0000
RecordIndex,17.0,23.352941,24.395033,1.0,11.0000,19.00000,24.00000,106.0000
Intensity,156710.0,0.327165,0.620027,0.0,0.0000,0.00000,1.00000,3.0000
Sugar,39.0,6.871795,10.778095,0.0,0.0000,0.00000,12.00000,50.0000

#### Step 11.1: Identify Out-of-Range Values

In [16]:
# Check impossible / out-of-range values

ranges = {
    "Libre GL": (40, 400),
    "Dexcom GL": (40, 400),
    "HR": (30, 176),
    "Calories (Activity)": (0, 16.178),
    "METs": (10, 176),
    "Calories": (30, 1180),
    "Carbs": (0, 176),
    "Protein": (3, 176),
    "Fat": (0, 176),
    "Fiber": (0, 176),
    "Amount Consumed": (0, 100)
}

for column, (min_val, max_val) in ranges.items():
    invalid = combined_cg[
        (combined_cg[column] < min_val) |
        (combined_cg[column] > max_val)
    ]

    print(column, ":", len(invalid), "invalid values")

Libre GL : 9 invalid values
Dexcom GL : 0 invalid values
HR : 0 invalid values
Calories (Activity) : 2 invalid values
METs : 3 invalid values
Calories : 85 invalid values
Carbs : 11 invalid values
Protein : 243 invalid values
Fat : 1 invalid values
Fiber : 23 invalid values
Amount Consumed : 131 invalid values

#### Step 11.2: Inspect Out-of-Range Values and Their Counts

In [17]:
for column, (min_val, max_val) in ranges.items():
    invalid_values = combined_cg.loc[
        (combined_cg[column] < min_val) |
        (combined_cg[column] > max_val),
        column
    ]

    if len(invalid_values) > 0:
        print("\n", column)
        print("Count:", len(invalid_values))
        print("Values:", invalid_values.unique())

 Libre GL
Count: 9
Values: [400.33333333 401.26666667 402.2        403.13333333 404.06666667
 405.         403.73333333 402.46666667 401.2       ]

 Calories (Activity)
Count: 2
Values: [16.17840004]

 METs
Count: 3
Values: [0.]

 Calories
Count: 85
Values: [1.700e+01 1.860e+03 1.240e+03 1.592e+03 2.250e+03 1.680e+03 2.015e+03
 1.734e+03 5.000e+00 1.254e+03 0.000e+00 2.000e+00 1.365e+03 1.460e+03
 1.289e+03 2.000e+01 1.590e+03 1.250e+03 8.000e+00 1.740e+03 1.736e+03
 1.530e+03 2.030e+03 1.000e+01 2.826e+03 1.375e+03 1.950e+03 2.400e+01
 1.282e+03 2.900e+01 2.400e+00 1.331e+03 1.473e+03 1.226e+03 3.000e+00
 1.205e+03 1.420e+03]

 Carbs
Count: 11
Values: [204. 229. 276. 190. 382. 255. 472. 282. 761. 201.]

 Protein
Count: 243
Values: [0.  2.  1.  1.9 2.7 1.3 1.6 0.6 0.1 0.3]

 Fat
Count: 1
Values: [508.]

 Fiber
Count: 23
Values: [ 480.  230.  510. 1020. 2830.  904. 2670.  950. 1086. 2300.  583.  460.
  180.  916. 1099.  400.  380. 1424. 2199.  520.  570.]

 Amount Consumed
Count: 131
Values: [200. 300. 400. 500. 150. 375. 700. 600. 900.]

#### 11.3 Investigate Amount Consumed Values

In [18]:
combined_cg[
    combined_cg["Amount Consumed"] > 100
][["subject", "Timestamp", "Meal Type", "Calories",
   "Carbs", "Protein", "Fat", "Fiber", "Amount Consumed"]]

,subject,Timestamp,Meal Type,Calories,Carbs,Protein,Fat,Fiber,Amount Consumed
90495,7,2023-11-04 19:16:00,dinner,442.0,49.0,40.0,4.0,0.0,200.0
91457,7,2023-11-05 19:18:00,dinner,341.0,29.0,29.0,13.0,0.0,200.0
92288,7,2023-11-06 18:54:00,dinner,590.0,46.0,44.0,52.0,7.0,300.0
94226,7,2023-11-09 18:30:00,dinner,659.0,40.0,24.0,25.0,17.0,400.0
431255,31,2022-06-30 19:30:00,snack,262.0,19.0,14.0,3.0,1.0,300.0
...,...,...,...,...,...,...,...,...,...
678702,49,2025-05-15 20:10:00,dinner,752.0,63.0,16.0,55.0,20.0,600.0
680102,49,2025-05-16 19:30:00,dinner,575.0,63.0,19.0,30.0,5.0,400.0
681529,49,2025-05-17 19:17:00,dinner,412.0,124.0,56.0,36.0,8.0,400.0
682994,49,2025-05-18 19:42:00,dinner,590.0,69.0,31.0,42.0,9.0,500.0
684473,49,2025-05-19 20:21:00,dinner,370.0,38.0,26.0,12.0,2.0,200.0

#### 11.3.1 Checking which file has the outliers of the Amount consumed

In [19]:
combined_cg.loc[
    combined_cg["Amount Consumed"] > 100,
    ["subject", "source_file", "Amount Consumed"]
].groupby(["subject", "source_file"]).size()

subject  source_file
7        CGMacros-007.csv     4
31       CGMacros-031.csv     7
33       CGMacros-033.csv     9
34       CGMacros-034.csv    14
35       CGMacros-035.csv     5
36       CGMacros-036.csv     7
38       CGMacros-038.csv     3
39       CGMacros-039.csv     8
41       CGMacros-041.csv     5
43       CGMacros-043.csv    19
44       CGMacros-044.csv    14
45       CGMacros-045.csv     5
46       CGMacros-046.csv     5
47       CGMacros-047.csv     7
48       CGMacros-048.csv    11
49       CGMacros-049.csv     8
dtype: int64

In [20]:
combined_cg["Amount Consumed"].value_counts().sort_index()

Amount Consumed
0.00        39
0.75         1
1.00       207
2.00        35
3.00        30
4.00        15
5.00         8
6.00         5
7.00         1
8.00         1
9.00         2
25.00        1
50.00        8
60.00        4
70.00        2
75.00       29
80.00        1
90.00        2
100.00    1120
150.00       1
200.00      39
300.00      42
375.00       1
400.00      21
500.00      11
600.00      13
700.00       2
900.00       1
Name: count, dtype: int64

#### 11.3.2 All Amount Consumed values for each affected subject

In [21]:
affected_subjects = combined_cg.loc[
    combined_cg["Amount Consumed"] > 100,
    "subject"
].unique()

for s in affected_subjects:
    print("\nSubject:", s)

    print(
        combined_cg.loc[
            combined_cg["subject"] == s,
            "Amount Consumed"
        ].value_counts().sort_index()
    )

Subject: 7
Amount Consumed
100.0    13
200.0     2
300.0     1
400.0     1
Name: count, dtype: int64

Subject: 31
Amount Consumed
0.0       5
50.0      2
75.0      1
100.0    39
200.0     4
300.0     3
Name: count, dtype: int64

Subject: 33
Amount Consumed
0.0       1
75.0      1
100.0    22
150.0     1
200.0     2
300.0     3
375.0     1
500.0     2
Name: count, dtype: int64

Subject: 34
Amount Consumed
75.0      1
100.0    34
200.0     2
300.0     5
400.0     4
600.0     2
700.0     1
Name: count, dtype: int64

Subject: 35
Amount Consumed
0.0       1
100.0    21
300.0     2
400.0     2
600.0     1
Name: count, dtype: int64

Subject: 36
Amount Consumed
100.0    23
200.0     2
300.0     3
400.0     2
Name: count, dtype: int64

Subject: 38
Amount Consumed
0.0       8
100.0    29
200.0     1
300.0     1
500.0     1
Name: count, dtype: int64

Subject: 39
Amount Consumed
0.0       6
100.0    20
200.0     1
300.0     2
400.0     1
500.0     2
600.0     1
900.0     1
Name: count, dtype: int64

Subject: 41
Amount Consumed
0.0       3
75.0      3
100.0    37
300.0     2
400.0     1
500.0     2
Name: count, dtype: int64

Subject: 43
Amount Consumed
100.0    45
200.0     4
300.0     6
400.0     4
500.0     1
600.0     4
Name: count, dtype: int64

Subject: 44
Amount Consumed
0.0       1
75.0      3
100.0    25
200.0     6
300.0     1
400.0     3
500.0     1
600.0     3
Name: count, dtype: int64

Subject: 45
Amount Consumed
0.0       3
1.0       1
75.0      2
100.0    21
200.0     1
300.0     3
600.0     1
Name: count, dtype: int64

Subject: 46
Amount Consumed
75.0      4
100.0    20
200.0     4
300.0     1
Name: count, dtype: int64

Subject: 47
Amount Consumed
75.0      3
100.0    19
200.0     3
300.0     4
Name: count, dtype: int64

Subject: 48
Amount Consumed
0.0       3
75.0      3
100.0    19
200.0     6
300.0     4
500.0     1
Name: count, dtype: int64

Subject: 49
Amount Consumed
75.0      3
100.0    17
200.0     1
300.0     1
400.0     3
500.0     1
600.0     1
700.0     1
Name: count, dtype: int64

#### Step 11.4: Create Outlier/Validation Flags

In [22]:
combined_cg["Amount_Consumed_Flag"] = (
    combined_cg["Amount Consumed"] > 100
)

In [23]:
combined_cg["Amount_Consumed_Flag"].value_counts().rename(
    index={True: "true", False: "false"}
)

Amount_Consumed_Flag
false    687449
true        131
Name: count, dtype: int64

In [24]:
combined_cg["Amount_Consumed_Flag"].value_counts()

Amount_Consumed_Flag
False    687449
True        131
Name: count, dtype: int64

#### Step 11.4 Investigate Fiber Values

In [25]:
combined_cg[
    combined_cg["Fiber"] > 176
][["subject", "Timestamp", "Meal Type", "Calories",
   "Carbs", "Protein", "Fat", "Fiber", "Amount Consumed"]]

,subject,Timestamp,Meal Type,Calories,Carbs,Protein,Fat,Fiber,Amount Consumed
220046,16,2023-07-14 11:58:00,snack,280.0,38.0,4.0,12.0,480.0,1.0
221501,16,2023-07-15 12:13:00,snack,460.0,45.0,12.0,23.0,230.0,3.0
222934,16,2023-07-16 12:06:00,snack,220.0,19.0,7.0,13.0,510.0,1.0
226048,16,2023-07-18 16:00:00,snack,580.0,73.0,7.0,31.0,230.0,2.0
227728,16,2023-07-19 20:00:00,dinner,440.0,38.0,14.0,26.0,1020.0,1.0
228928,16,2023-07-20 16:00:00,snack,410.0,63.0,6.0,15.0,480.0,1.0
229168,16,2023-07-20 20:00:00,dinner,1590.0,107.0,54.0,508.0,2830.0,2.0
230608,16,2023-07-21 20:00:00,dinner,1250.0,17.0,44.0,27.0,904.0,3.0
232048,16,2023-07-22 20:00:00,dinner,870.0,110.0,69.0,28.0,2670.0,4.0
233488,16,2023-07-23 20:00:00,dinner,540.0,45.0,25.0,28.0,950.0,1.0
268334,19,2020-09-30 16:06:00,dinner,630.0,55.0,42.0,27.0,1086.0,5.0
269922,19,2020-10-01 18:34:00,dinner,1460.0,100.0,62.0,90.0,2300.0,1.0
271534,19,2020-10-02 21:26:00,dinner,360.0,79.0,6.0,4.0,583.0,2.0
272753,19,2020-10-03 18:00:00,snack,260.0,44.0,2.0,8.0,460.0,2.0
272937,19,2020-10-03 21:04:00,snack,162.0,16.0,2.0,10.0,180.0,1.0
274188,19,2020-10-04 17:55:00,dinner,613.0,43.0,39.0,33.0,916.0,2.0
275555,19,2020-10-05 16:42:00,dinner,1003.0,138.0,46.0,33.0,1099.0,3.0
275862,19,2020-10-05 21:49:00,snack,80.0,0.0,2.0,5.0,400.0,1.0
276970,19,2020-10-06 16:17:00,snack,140.0,16.0,2.0,8.0,380.0,1.0
277114,19,2020-10-06 18:41:00,dinner,448.0,54.0,35.0,13.0,1424.0,3.0
278541,19,2020-10-07 18:28:00,dinner,768.0,65.0,78.0,26.0,2199.0,2.0
279865,19,2020-10-08 16:32:00,snack,280.0,40.0,4.0,14.0,520.0,1.0
279966,19,2020-10-08 18:13:00,dinner,323.0,40.0,33.0,3.0,570.0,3.0

#### 11:4.1 Checking which file has the outliers of the Fiber

In [26]:
combined_cg.loc[
    combined_cg["Fiber"] > 176,
    ["subject", "source_file", "Fiber"]
].groupby(["subject", "source_file"]).size()

subject  source_file
16       CGMacros-016.csv    10
19       CGMacros-019.csv    13
dtype: int64

#### All Fiber values for each affected subject

In [27]:
affected_fiber_subjects = combined_cg.loc[
    combined_cg["Fiber"] > 176,
    "subject"
].unique()

for s in affected_fiber_subjects:
    print("\nSubject:", s)
    print(
        combined_cg.loc[
            combined_cg["subject"] == s,
            "Fiber"
        ].value_counts().sort_index()
    )

Subject: 16
Fiber
0.0       9
4.0       1
5.0       1
7.0       2
11.0      1
13.0      2
20.0      1
55.0      1
230.0     2
480.0     2
510.0     1
904.0     1
950.0     1
1020.0    1
2670.0    1
2830.0    1
Name: count, dtype: int64

Subject: 19
Fiber
0.0       12
1.0        1
2.0        1
4.0        3
5.0        3
7.0        2
10.0       2
11.0       1
12.0       1
13.0       2
15.0       1
18.0       1
29.0       1
30.0       1
60.0       1
100.0      1
174.0      1
180.0      1
380.0      1
400.0      1
460.0      1
520.0      1
570.0      1
583.0      1
916.0      1
1086.0     1
1099.0     1
1424.0     1
2199.0     1
2300.0     1
Name: count, dtype: int64

#### Step 11:5 Checking outliers in Fat column

In [28]:
combined_cg.loc[
    (combined_cg["Fat"] < 0) |
    (combined_cg["Fat"] > 176),
    ["subject", "Timestamp", "Meal Type",
     "Calories", "Carbs", "Protein", "Fat", "Fiber"]
]

,subject,Timestamp,Meal Type,Calories,Carbs,Protein,Fat,Fiber
229168,16,2023-07-20 20:00:00,dinner,1590.0,107.0,54.0,508.0,2830.0

#### Step 11:6 Checking overall outliers in Nutrition columns

In [29]:
combined_cg["Nutrition_Outlier_Flag"] = (
    (combined_cg["Calories"] < 0) |
    (combined_cg["Calories"] > 1180) |
    (combined_cg["Carbs"] < 0) |
    (combined_cg["Carbs"] > 176) |
    (combined_cg["Protein"] < 0) |
    (combined_cg["Protein"] > 176) |
    (combined_cg["Fat"] < 0) |
    (combined_cg["Fat"] > 176) |
    (combined_cg["Fiber"] < 0) |
    (combined_cg["Fiber"] > 176)
)

In [30]:
combined_cg["Nutrition_Outlier_Flag"].value_counts()

Nutrition_Outlier_Flag
False    687528
True         52
Name: count, dtype: int64

In [31]:
combined_cg.loc[
    combined_cg["Nutrition_Outlier_Flag"],
    ["subject", "Timestamp", "Meal Type",
     "Calories", "Carbs", "Protein", "Fat", "Fiber"]
]

,subject,Timestamp,Meal Type,Calories,Carbs,Protein,Fat,Fiber
51240,4,2023-09-14 19:54:00,Dinner,1860.0,204.0,102.0,72.0,9.0
52569,4,2023-09-15 18:03:00,Dinner,1240.0,136.0,68.0,48.0,6.0
56914,4,2023-09-18 18:28:00,Dinner,1592.0,229.0,27.0,67.0,16.0
58345,4,2023-09-19 18:19:00,Dinner,2250.0,124.0,116.0,141.0,16.0
97198,8,2023-01-31 20:40:00,dinner,1680.0,168.0,50.0,110.0,0.0
105724,8,2023-02-06 18:46:00,dinner,2015.0,42.0,12.0,86.0,0.0
107111,8,2023-02-07 17:53:00,dinner,1734.0,78.0,148.0,91.0,15.0
123514,9,2020-09-24 19:29:00,dinner,1254.0,133.0,32.0,67.0,8.0
148164,11,2020-10-08 17:50:00,dinner,1365.0,163.0,68.0,31.0,30.0
149597,11,2020-10-09 17:43:00,dinner,1460.0,168.0,56.0,56.0,8.0
181854,13,2024-02-02 15:41:00,dinner,1289.0,147.0,84.0,50.0,15.0
220046,16,2023-07-14 11:58:00,snack,280.0,38.0,4.0,12.0,480.0
221501,16,2023-07-15 12:13:00,snack,460.0,45.0,12.0,23.0,230.0
222934,16,2023-07-16 12:06:00,snack,220.0,19.0,7.0,13.0,510.0
226048,16,2023-07-18 16:00:00,snack,580.0,73.0,7.0,31.0,230.0
227728,16,2023-07-19 20:00:00,dinner,440.0,38.0,14.0,26.0,1020.0
228928,16,2023-07-20 16:00:00,snack,410.0,63.0,6.0,15.0,480.0
229168,16,2023-07-20 20:00:00,dinner,1590.0,107.0,54.0,508.0,2830.0
230608,16,2023-07-21 20:00:00,dinner,1250.0,17.0,44.0,27.0,904.0
232048,16,2023-07-22 20:00:00,dinner,870.0,110.0,69.0,28.0,2670.0
233488,16,2023-07-23 20:00:00,dinner,540.0,45.0,25.0,28.0,950.0
249859,17,2023-10-19 21:00:00,dinner,1740.0,131.0,36.0,11.0,12.0
253887,18,2024-02-07 18:39:00,Dinner,1736.0,276.0,108.0,66.0,53.0
268334,19,2020-09-30 16:06:00,dinner,630.0,55.0,42.0,27.0,1086.0
269922,19,2020-10-01 18:34:00,dinner,1460.0,100.0,62.0,90.0,2300.0
271534,19,2020-10-02 21:26:00,dinner,360.0,79.0,6.0,4.0,583.0
272753,19,2020-10-03 18:00:00,snack,260.0,44.0,2.0,8.0,460.0
272937,19,2020-10-03 21:04:00,snack,162.0,16.0,2.0,10.0,180.0
274188,19,2020-10-04 17:55:00,dinner,613.0,43.0,39.0,33.0,916.0
275555,19,2020-10-05 16:42:00,dinner,1003.0,138.0,46.0,33.0,1099.0
275862,19,2020-10-05 21:49:00,snack,80.0,0.0,2.0,5.0,400.0
276970,19,2020-10-06 16:17:00,snack,140.0,16.0,2.0,8.0,380.0
277114,19,2020-10-06 18:41:00,dinner,448.0,54.0,35.0,13.0,1424.0
278541,19,2020-10-07 18:28:00,dinner,768.0,65.0,78.0,26.0,2199.0
279865,19,2020-10-08 16:32:00,snack,280.0,40.0,4.0,14.0,520.0
279966,19,2020-10-08 18:13:00,dinner,323.0,40.0,33.0,3.0,570.0
285722,20,2024-03-22 16:28:00,dinner,1530.0,190.0,46.0,69.0,15.0
291652,20,2024-03-26 19:18:00,dinner,2030.0,38.0,19.0,100.0,3.0
299301,21,2020-06-09 20:23:00,dinner,470.0,382.0,28.0,22.0,6.0
300785,21,2020-06-10 21:07:00,snack,1050.0,255.0,15.0,0.0,0.0
302184,21,2020-06-11 20:26:00,dinner,230.0,190.0,14.0,11.0,3.0
310850,21,2020-06-17 20:52:00,dinner,2826.0,472.0,53.0,109.0,16.0
310931,21,2020-06-17 22:13:00,snack,1116.0,282.0,19.0,3.0,38.0
313966,22,2021-03-28 20:00:00,dinner,1375.0,84.0,40.0,55.0,6.0
340102,23,2021-05-11 18:19:00,dinner,1950.0,106.0,94.0,88.0,2.0
388755,28,2023-12-05 20:39:00,dinner,1282.0,8.0,58.0,90.0,0.0
505578,36,2022-03-31 16:36:00,dinner,1030.0,761.0,62.0,53.0,12.0
534426,39,2025-02-07 17:54:00,dinner,1331.0,87.0,96.0,66.0,12.0
587875,43,2025-10-19 21:24:00,dinner,1473.0,201.0,40.0,62.0,7.0
590503,43,2025-10-21 17:12:00,dinner,1226.0,109.0,52.0,68.0,3.0
649752,47,2025-11-06 16:06:00,dinner,1205.0,95.0,84.0,60.0,8.0
658507,48,2022-11-16 21:11:00,dinner,1420.0,93.0,56.0,83.0,5.0

In [32]:
combined_cg["Nutrition_Outlier_Flag"].value_counts().rename(
    index={True: "true", False: "false"}
)

Nutrition_Outlier_Flag
false    687528
true         52
Name: count, dtype: int64

#### Checking which column is causing the flag most often

In [33]:
print("Calories:", ((combined_cg["Calories"] < 0) | (combined_cg["Calories"] > 1180)).sum())
print("Carbs:", ((combined_cg["Carbs"] < 0) | (combined_cg["Carbs"] > 176)).sum())
print("Protein:", ((combined_cg["Protein"] < 0) | (combined_cg["Protein"] > 176)).sum())
print("Fat:", ((combined_cg["Fat"] < 0) | (combined_cg["Fat"] > 176)).sum())
print("Fiber:", ((combined_cg["Fiber"] < 0) | (combined_cg["Fiber"] > 176)).sum())

Calories: 27
Carbs: 11
Protein: 0
Fat: 1
Fiber: 23

#### Step 11:7 Checking outliers in METs column

In [34]:
combined_cg.loc[
    combined_cg["METs"] == 0,
    ["subject", "Timestamp", "HR", "Calories (Activity)", "METs"]
]

        subject           Timestamp  HR  Calories (Activity)  METs
75032         5 2020-08-27 11:51:00 NaN                  0.0   0.0
89489         6 2023-04-17 11:53:00 NaN                  0.0   0.0
109665        8 2023-02-09 12:27:00 NaN                  0.0   0.0

#### Considering those outliers as NAN

In [35]:
import numpy as np

combined_cg.loc[
    combined_cg["METs"] == 0,
    "METs"
] = np.nan

In [36]:
combined_cg.loc[
    combined_cg["subject"].isin([5, 6, 8]),
    ["subject", "Timestamp", "METs"]
]

        subject           Timestamp  METs
60595         5 2020-08-17 11:14:00  11.0
60596         5 2020-08-17 11:15:00  11.0
60597         5 2020-08-17 11:16:00  11.0
60598         5 2020-08-17 11:17:00  11.0
60599         5 2020-08-17 11:18:00  26.0
...         ...                 ...   ...
109925        8 2023-02-09 16:47:00   NaN
109926        8 2023-02-09 16:48:00   NaN
109927        8 2023-02-09 16:49:00   NaN
109928        8 2023-02-09 16:50:00   NaN
109929        8 2023-02-09 16:51:00   NaN

[43680 rows x 3 columns]

In [37]:
print("METs below 10:", (combined_cg["METs"] < 10).sum())
print("Missing METs:", combined_cg["METs"].isna().sum())

METs below 10: 0
Missing METs: 186505

In [38]:
combined_cg.isnull().sum()

subject                        0
source_file                    0
Timestamp                      0
Libre GL                     220
Dexcom GL                  57755
HR                         77324
Calories (Activity)        35446
METs                      186505
Meal Type                 685874
Calories                  685874
Carbs                     685874
Protein                   685874
Fat                       685874
Fiber                     685875
Amount Consumed           685938
Image path                684383
Steps                     681925
RecordIndex               687563
Intensity                 530870
Sugar                     687541
Timestamp_original             0
Amount_Consumed_Flag           0
Nutrition_Outlier_Flag         0
dtype: int64

#### Step 11:8 Standardize Blank and Whitespace Values as Missing Data

#### Step 11:9 Checking for outliers in Libre GL column

In [39]:
combined_cg.loc[
    (combined_cg["Libre GL"] < 40) |
    (combined_cg["Libre GL"] > 400),
    ["subject", "Timestamp", "Libre GL", "Dexcom GL"]
]

        subject           Timestamp    Libre GL  Dexcom GL
415865       30 2021-01-24 10:07:00  400.333333      315.4
415866       30 2021-01-24 10:08:00  401.266667      312.2
415867       30 2021-01-24 10:09:00  402.200000      309.0
415868       30 2021-01-24 10:10:00  403.133333      306.4
415869       30 2021-01-24 10:11:00  404.066667      303.8
415870       30 2021-01-24 10:12:00  405.000000      301.2
415871       30 2021-01-24 10:13:00  403.733333      298.6
415872       30 2021-01-24 10:14:00  402.466667      296.0
415873       30 2021-01-24 10:15:00  401.200000      295.4

#### Step 11.10 Correcting Out-of-Range Libre GL Values Using Linear Interpolation

In [40]:
import pandas as pd

# ---------------------------------------------------
# Step: Correct Subject 30 Libre GL and Recalculate
# Adjacent 1-minute Values Using Linear Interpolation
# ---------------------------------------------------

subject_id = 30

prev_time = pd.Timestamp("2021-01-24 09:57:00")
mid_time  = pd.Timestamp("2021-01-24 10:12:00")
next_time = pd.Timestamp("2021-01-24 10:27:00")

prev_value = 391
corrected_mid_value = 400
next_value = 386

# IMPORTANT:
# Use the EXISTING column name "Libre GL"
# Do NOT create a new column such as "Libre_Gl"

# First interval: 09:57 to 10:12
mask1 = (
    (combined_cg["subject"] == subject_id) &
    (combined_cg["Timestamp"].between(prev_time, mid_time))
)

mins1 = (
    combined_cg.loc[mask1, "Timestamp"] - prev_time
).dt.total_seconds() / 60

total1 = (
    mid_time - prev_time
).total_seconds() / 60

combined_cg.loc[mask1, "Libre GL"] = (
    prev_value
    + (corrected_mid_value - prev_value) * (mins1 / total1)
).round(2)


# Second interval: 10:12 to 10:27
mask2 = (
    (combined_cg["subject"] == subject_id) &
    (combined_cg["Timestamp"].between(mid_time, next_time))
)

mins2 = (
    combined_cg.loc[mask2, "Timestamp"] - mid_time
).dt.total_seconds() / 60

total2 = (
    next_time - mid_time
).total_seconds() / 60

combined_cg.loc[mask2, "Libre GL"] = (
    corrected_mid_value
    + (next_value - corrected_mid_value) * (mins2 / total2)
).round(2)


# Verify corrected values
display(
    combined_cg.loc[
        (combined_cg["subject"] == subject_id) &
        (combined_cg["Timestamp"].between(prev_time, next_time)),
        ["subject", "Timestamp", "Libre GL"]
    ]
)

# Verify no values remain above documented Libre GL maximum
print(
    "Libre GL values above 400:",
    (combined_cg["Libre GL"] > 400).sum()
)

        subject           Timestamp  Libre GL
415855       30 2021-01-24 09:57:00    391.00
415856       30 2021-01-24 09:58:00    391.60
415857       30 2021-01-24 09:59:00    392.20
415858       30 2021-01-24 10:00:00    392.80
415859       30 2021-01-24 10:01:00    393.40
415860       30 2021-01-24 10:02:00    394.00
415861       30 2021-01-24 10:03:00    394.60
415862       30 2021-01-24 10:04:00    395.20
415863       30 2021-01-24 10:05:00    395.80
415864       30 2021-01-24 10:06:00    396.40
415865       30 2021-01-24 10:07:00    397.00
415866       30 2021-01-24 10:08:00    397.60
415867       30 2021-01-24 10:09:00    398.20
415868       30 2021-01-24 10:10:00    398.80
415869       30 2021-01-24 10:11:00    399.40
415870       30 2021-01-24 10:12:00    400.00
415871       30 2021-01-24 10:13:00    399.07
415872       30 2021-01-24 10:14:00    398.13
415873       30 2021-01-24 10:15:00    397.20
415874       30 2021-01-24 10:16:00    396.27
415875       30 2021-01-24 10:17:00    395.33
415876       30 2021-01-24 10:18:00    394.40
415877       30 2021-01-24 10:19:00    393.47
415878       30 2021-01-24 10:20:00    392.53
415879       30 2021-01-24 10:21:00    391.60
415880       30 2021-01-24 10:22:00    390.67
415881       30 2021-01-24 10:23:00    389.73
415882       30 2021-01-24 10:24:00    388.80
415883       30 2021-01-24 10:25:00    387.87
415884       30 2021-01-24 10:26:00    386.93
415885       30 2021-01-24 10:27:00    386.00

Libre GL values above 400: 0

In [41]:
combined_cg.loc[
    (combined_cg["subject"] == 30) &
    (combined_cg["Timestamp"].between(
        "2021-01-24 09:57:00",
        "2021-01-24 10:27:00"
    )),
    ["subject", "Timestamp", "Libre GL"]
]

        subject           Timestamp  Libre GL
415855       30 2021-01-24 09:57:00    391.00
415856       30 2021-01-24 09:58:00    391.60
415857       30 2021-01-24 09:59:00    392.20
415858       30 2021-01-24 10:00:00    392.80
415859       30 2021-01-24 10:01:00    393.40
415860       30 2021-01-24 10:02:00    394.00
415861       30 2021-01-24 10:03:00    394.60
415862       30 2021-01-24 10:04:00    395.20
415863       30 2021-01-24 10:05:00    395.80
415864       30 2021-01-24 10:06:00    396.40
415865       30 2021-01-24 10:07:00    397.00
415866       30 2021-01-24 10:08:00    397.60
415867       30 2021-01-24 10:09:00    398.20
415868       30 2021-01-24 10:10:00    398.80
415869       30 2021-01-24 10:11:00    399.40
415870       30 2021-01-24 10:12:00    400.00
415871       30 2021-01-24 10:13:00    399.07
415872       30 2021-01-24 10:14:00    398.13
415873       30 2021-01-24 10:15:00    397.20
415874       30 2021-01-24 10:16:00    396.27
415875       30 2021-01-24 10:17:00    395.33
415876       30 2021-01-24 10:18:00    394.40
415877       30 2021-01-24 10:19:00    393.47
415878       30 2021-01-24 10:20:00    392.53
415879       30 2021-01-24 10:21:00    391.60
415880       30 2021-01-24 10:22:00    390.67
415881       30 2021-01-24 10:23:00    389.73
415882       30 2021-01-24 10:24:00    388.80
415883       30 2021-01-24 10:25:00    387.87
415884       30 2021-01-24 10:26:00    386.93
415885       30 2021-01-24 10:27:00    386.00

#### Step 11.11 Reviewing Protein Values Below the Documented Range

In [42]:
combined_cg.loc[
    combined_cg["Protein"] < 3,
    ["subject", "Timestamp", "Meal Type",
     "Calories", "Carbs", "Protein", "Fat", "Fiber"]
]

,subject,Timestamp,Meal Type,Calories,Carbs,Protein,Fat,Fiber
618,1,2020-05-01 20:48:00,Dinner,80.0,18.0,0.0,0.0,0.0
825,1,2020-05-02 00:15:00,Snacks,110.0,24.0,0.0,2.0,0.0
1807,1,2020-05-02 16:37:00,Snacks,38.0,9.0,0.0,0.0,0.0
2253,1,2020-05-03 00:03:00,Snacks,160.0,29.0,2.0,4.0,0.0
3498,1,2020-05-03 20:48:00,Snacks,90.0,22.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
617411,45,2025-03-31 16:00:00,snack,170.0,20.0,2.0,10.0,1.0
622046,45,2025-04-03 21:15:00,snack,170.0,20.0,2.0,10.0,1.0
632221,46,2025-05-06 16:23:00,dinner,290.0,22.0,2.0,0.0,0.0
655511,48,2022-11-14 19:00:00,dinner,20.0,2.0,0.0,2.0,2.0
662475,48,2022-11-19 15:19:00,snack,31.0,8.0,0.0,0.0,0.0

In [43]:
combined_cg.loc[
    combined_cg["Protein"] < 3,
    "Protein"
].value_counts().sort_index()

Protein
0.0    107
0.1      1
0.3      1
0.6      1
1.0     71
1.3      1
1.6      1
1.9      1
2.0     58
2.7      1
Name: count, dtype: int64

In [44]:
combined_cg.loc[
    combined_cg["Protein"] < 3,
    "Meal Type"
].value_counts(dropna=False)

Meal Type
snack     141
dinner     64
Snacks     22
Dinner     15
Snack       1
Name: count, dtype: int64

### Step 12. Check Categorical Consistency — Meal Type

In [45]:
combined_cg["Meal Type"].value_counts(dropna=False)

Meal Type
NaN          685874
dinner          418
snack           300
lunch           272
breakfast       266
Breakfast       170
Lunch           163
Dinner           74
Snacks           38
Snack             4
snack 1           1
Name: count, dtype: int64

In [46]:
combined_cg["Meal Type"] = (
    combined_cg["Meal Type"]
    .str.strip()
    .str.lower()
    .replace({
        "snacks": "snack",
        "snack 1": "snack"
    })
)

### Step 13: Remove Unnecessary Columns

In [47]:
combined_cg.drop(
    columns=["RecordIndex", "Image path", "Timestamp_original"],
    inplace=True,
    errors="ignore"
)

In [48]:
"Timestamp_original" in combined_cg.columns

False

### Step 14: Standardize Final Column Names

In [49]:
combined_cg.columns = (
    combined_cg.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^\w\s]", "", regex=True)
    .str.replace(r"\s+", "_", regex=True)
    .str.replace(r"_+", "_", regex=True)
    .str.strip("_")
)

In [50]:
combined_cg.columns.tolist()

['subject',
 'source_file',
 'timestamp',
 'libre_gl',
 'dexcom_gl',
 'hr',
 'calories_activity',
 'mets',
 'meal_type',
 'calories',
 'carbs',
 'protein',
 'fat',
 'fiber',
 'amount_consumed',
 'steps',
 'intensity',
 'sugar',
 'amount_consumed_flag',
 'nutrition_outlier_flag']

In [51]:
import numpy as np

combined_cg[["hr", "intensity", "mets", "steps", "calories_activity", "libre_gl", "dexcom_gl", "calories", "carbs", "protein", "fat", "fiber", "sugar"]] = (
    combined_cg[["hr", "intensity", "mets", "steps", "calories_activity", "libre_gl", "dexcom_gl", "calories", "carbs", "protein", "fat", "fiber", "sugar"]]
    .replace(r"^\s*$", np.nan, regex=True)
)

### Step 15: Check Logical Consistency

#### Step 15.1 Meal Type with nutrition values

In [52]:
combined_cg.loc[
    combined_cg["meal_type"].notna() &
    combined_cg[["calories", "carbs", "protein", "fat", "fiber"]]
        .isna().all(axis=1),
    ["subject", "timestamp", "meal_type",
     "calories", "carbs", "protein", "fat", "fiber"]
]

Empty DataFrame
Columns: [subject, timestamp, meal_type, calories, carbs, protein, fat, fiber]
Index: []

#### Step 15.2 Nutrition values without Meal Type

In [53]:
combined_cg.loc[
    combined_cg["meal_type"].isna() &
    combined_cg[["calories", "carbs", "protein", "fat", "fiber"]]
        .notna().any(axis=1),
    ["subject", "timestamp", "meal_type",
     "calories", "carbs", "protein", "fat", "fiber"]
]

Empty DataFrame
Columns: [subject, timestamp, meal_type, calories, carbs, protein, fat, fiber]
Index: []

#### Step 15.3 Amount Consumed consistency

In [54]:
combined_cg.loc[
    combined_cg["meal_type"].isna() &
    combined_cg["amount_consumed"].notna(),
    ["subject", "timestamp", "meal_type", "amount_consumed"]
]

Empty DataFrame
Columns: [subject, timestamp, meal_type, amount_consumed]
Index: []

In [55]:
combined_cg.loc[
    combined_cg["meal_type"].notna() &
    combined_cg["amount_consumed"].isna(),
    ["subject", "timestamp", "meal_type", "amount_consumed"]
]

        subject           timestamp  meal_type  amount_consumed
378196       28 2023-11-28 12:40:00      lunch              NaN
378589       28 2023-11-28 19:13:00     dinner              NaN
378741       28 2023-11-28 21:45:00      snack              NaN
379420       28 2023-11-29 09:04:00  breakfast              NaN
379647       28 2023-11-29 12:51:00      lunch              NaN
...         ...                 ...        ...              ...
408676       29 2024-01-25 16:34:00     dinner              NaN
409459       29 2024-01-26 05:37:00  breakfast              NaN
409821       29 2024-01-26 11:39:00      lunch              NaN
410215       29 2024-01-26 18:13:00     dinner              NaN
410953       29 2024-01-27 06:31:00  breakfast              NaN

[64 rows x 4 columns]

In [56]:
combined_cg.loc[
    combined_cg["meal_type"].notna() &
    combined_cg["amount_consumed"].isna()
].shape[0]

64

#### Step 15.4 Negative physiological/activity values

In [57]:
columns_to_check = [
    "libre_gl",
    "dexcom_gl",
    "hr",
    "calories_activity",
    "mets",
 'calories',
 'carbs',
 'protein',
 'fat',
 'fiber',
 'amount_consumed',
 'steps',
 'intensity',
 'sugar',
]

for col in columns_to_check:
    negative_count = (combined_cg[col] < 0).sum()
    print(col, ":", negative_count)

libre_gl : 0
dexcom_gl : 0
hr : 0
calories_activity : 0
mets : 0
calories : 0
carbs : 0
protein : 0
fat : 0
fiber : 0
amount_consumed : 0
steps : 0
intensity : 0
sugar : 0

### Step 16: Standardize Numeric Precision

In [58]:
combined_cg["libre_gl"] = combined_cg["libre_gl"].round(2)
combined_cg["calories_activity"] = combined_cg["calories_activity"].round(4)

In [59]:
combined_cg[["libre_gl", "calories_activity"]].head(10)

   libre_gl  calories_activity
0     84.00             1.0484
1     84.13             1.0484
2     84.27             1.0484
3     84.40             1.0484
4     84.53             1.0484
5     84.67             1.0484
6     84.80             1.1532
7     84.93             1.0484
8     85.07             1.0484
9     85.20             1.0484

### Step 17: Final Duplicate Check

In [60]:
combined_cg.duplicated().sum()

0

### Step 18: Final Cleaned-Data Review

In [61]:
combined_cg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 687580 entries, 0 to 687579
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   subject                 687580 non-null  int64
 1   source_file             687580 non-null  object
 2   timestamp               687580 non-null  datetime64[ns]
 3   libre_gl                687360 non-null  float64
 4   dexcom_gl               629825 non-null  float64
 5   hr                      610256 non-null  float64
 6   calories_activity       652134 non-null  float64
 7   mets                    501075 non-null  float64
 8   meal_type               1706 non-null    object
 9   calories                1706 non-null    float64
 10  carbs                   1706 non-null    float64
 11  protein                 1706 non-null    float64
 12  fat                     1706 non-null    float64
 13  fiber                   1705 non-null    float64
 14  amount_consumed         1642 non-null    float64
 15  steps                   5655 non-null    float64
 16  intensity               156710 non-null  float64
 17  sugar                   39 non-null      float64
 18  amount_consumed_flag    687580 non-null  bool
 19  nutrition_outlier_flag  687580 non-null  bool
dtypes: bool(2), datetime64[ns](1), float64(14), int64(1), object(2)
memory usage: 95.7+ MB

In [62]:
combined_cg.describe()

,subject,timestamp,libre_gl,dexcom_gl,hr,calories_activity,mets,calories,carbs,protein,fat,fiber,amount_consumed,steps,intensity,sugar
count,687580.000000,687580,687360.000000,629825.000000,610256.000000,652134.000000,501075.000000,1706.000000,1706.000000,1706.000000,1706.000000,1705.000000,1642.000000,5655.000000,156710.000000,39.000000
mean,24.709961,2022-11-22 16:35:56.972687104,109.055828,140.873351,78.830738,1.835610,17.212679,505.858968,52.080715,29.247421,19.783763,17.897243,97.865865,8.160743,0.327165,6.871795
min,1.000000,2019-11-15 20:12:00,40.000000,40.000000,30.000000,0.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,13.000000,2021-04-03 04:54:45,83.400000,113.000000,68.000000,1.011400,10.000000,268.000000,24.000000,10.000000,10.000000,0.000000,100.000000,0.000000,0.000000,0.000000
50%,23.000000,2023-02-03 09:26:30,100.200000,130.800000,79.000000,1.178200,11.000000,448.000000,50.000000,22.000000,14.000000,4.000000,100.000000,0.000000,0.000000,0.000000
75%,36.000000,2024-02-03 15:16:15,125.000000,157.200000,88.000000,1.871900,15.000000,712.000000,73.000000,44.000000,30.000000,7.000000,100.000000,0.000000,1.000000,12.000000
max,49.000000,2025-11-10 06:18:00,400.000000,400.000000,176.000000,16.178400,132.000000,2826.000000,761.000000,148.000000,508.000000,2830.000000,900.000000,116.000000,3.000000,50.000000
std,14.309624,NaN,41.278988,42.026542,15.294763,1.464122,13.142757,329.540743,40.066376,25.662044,20.752374,143.671402,91.665339,22.200962,0.620027,10.778095

In [63]:
combined_cg.head(20)

,subject,source_file,timestamp,libre_gl,dexcom_gl,hr,calories_activity,mets,meal_type,calories,carbs,protein,fat,fiber,amount_consumed,steps,intensity,sugar,amount_consumed_flag,nutrition_outlier_flag
0,1,CGMacros-001.csv,2020-05-01 10:30:00,84.00,NaN,56.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
1,1,CGMacros-001.csv,2020-05-01 10:31:00,84.13,NaN,56.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
2,1,CGMacros-001.csv,2020-05-01 10:32:00,84.27,NaN,57.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
3,1,CGMacros-001.csv,2020-05-01 10:33:00,84.40,NaN,54.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
4,1,CGMacros-001.csv,2020-05-01 10:34:00,84.53,NaN,55.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
5,1,CGMacros-001.csv,2020-05-01 10:35:00,84.67,NaN,57.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
6,1,CGMacros-001.csv,2020-05-01 10:36:00,84.80,NaN,59.0,1.1532,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
7,1,CGMacros-001.csv,2020-05-01 10:37:00,84.93,NaN,57.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
8,1,CGMacros-001.csv,2020-05-01 10:38:00,85.07,NaN,57.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
9,1,CGMacros-001.csv,2020-05-01 10:39:00,85.20,NaN,57.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
10,1,CGMacros-001.csv,2020-05-01 10:40:00,85.33,NaN,55.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
11,1,CGMacros-001.csv,2020-05-01 10:41:00,85.47,NaN,59.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
12,1,CGMacros-001.csv,2020-05-01 10:42:00,85.60,NaN,58.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
13,1,CGMacros-001.csv,2020-05-01 10:43:00,85.73,NaN,56.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
14,1,CGMacros-001.csv,2020-05-01 10:44:00,85.87,NaN,56.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
15,1,CGMacros-001.csv,2020-05-01 10:45:00,86.00,NaN,56.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
16,1,CGMacros-001.csv,2020-05-01 10:46:00,85.53,NaN,55.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
17,1,CGMacros-001.csv,2020-05-01 10:47:00,85.07,NaN,62.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
18,1,CGMacros-001.csv,2020-05-01 10:48:00,84.60,NaN,54.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
19,1,CGMacros-001.csv,2020-05-01 10:49:00,84.13,NaN,57.0,1.0484,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False

### Step 19: Export Cleaned DataFrame to CSV

In [64]:
combined_cg.to_csv(
    "DataMiners06_CGMacros_CleanedData.csv",
    index=False
)

In [65]:
import os

filename = "DataMiners06_CGMacros_CleanedData.csv"

print("File exists:", os.path.exists(filename))
print("File size:", os.path.getsize(filename))

File exists: True
File size: 62024532

# Part 2: Microbes Cleaning

### Step 1: Load the Raw Microbes File

In [4]:
import pandas as pd
microbes = pd.read_csv(
    r"C:\Users\karth\Downloads\CGMacros_Datathon_Aug_2026\Datathon_Aug_2026\microbes.csv"
)

### Step 2: Check Number of Rows and Columns

In [5]:
microbes.shape

(45, 1980)

### Step 3: Check Column Names and Data Types

In [6]:
microbes.dtypes.value_counts()

float64    1979
int64         1
Name: count, dtype: int64

#### 3.1 Checking that all non-missing values are only 0 or 1

In [7]:
microbe_cols = microbes.columns.drop("subject")

valid_binary = microbes[microbe_cols].isin([0, 1]) | microbes[microbe_cols].isna()

print(valid_binary.all().all())

True

#### 3.2 Changing the data type

In [8]:
microbe_cols = microbes.columns.drop("subject")

for col in microbe_cols:
    microbes[col] = microbes[col].astype("Int64")

In [9]:
microbes.dtypes.value_counts()

Int64    1979
int64       1
Name: count, dtype: int64

### Step 4: Check for Missing Values

In [10]:
print("Total missing values:", microbes.isna().sum().sum())
print("Columns with missing values:", (microbes.isna().sum() > 0).sum())

Total missing values: 1979
Columns with missing values: 1979

In [11]:
microbes[microbes.isna().any(axis=1)]

,subject,Abiotrophia defectiva,Abiotrophia sp. HMSC24B09,Acetivibrio ethanolgignens,Acetivibrio ethanolgignens strain ACET-33324,Achromobacter,Acidaminococcus intestini RyC-MR95,Acidaminococcus sp. BV3L6,Acidaminococcus sp. D21,Acidaminococcus sp. HPA0509,...,[Eubacterium] rectale strain T1-815,[Eubacterium] siraeum DSM 15702,[Eubacterium] siraeum strain 2789STDY5834928,[Propionibacterium] namnetense,[Ruminococcus] gnavus ATCC 29149,[Ruminococcus] torques strain 2789STDY5608833,[Ruminococcus] torques strain 2789STDY5608867,[Ruminococcus] torques strain 2789STDY5834841,[Ruminococcus] torques strain 2789STDY5834889,bacterium LF-3
43,48,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

#### 4.1 Retain Subject with Entirely Missing Microbiome Data

In [12]:
microbes.loc[
    microbes["subject"] == 48
]

,subject,Abiotrophia defectiva,Abiotrophia sp. HMSC24B09,Acetivibrio ethanolgignens,Acetivibrio ethanolgignens strain ACET-33324,Achromobacter,Acidaminococcus intestini RyC-MR95,Acidaminococcus sp. BV3L6,Acidaminococcus sp. D21,Acidaminococcus sp. HPA0509,...,[Eubacterium] rectale strain T1-815,[Eubacterium] siraeum DSM 15702,[Eubacterium] siraeum strain 2789STDY5834928,[Propionibacterium] namnetense,[Ruminococcus] gnavus ATCC 29149,[Ruminococcus] torques strain 2789STDY5608833,[Ruminococcus] torques strain 2789STDY5608867,[Ruminococcus] torques strain 2789STDY5834841,[Ruminococcus] torques strain 2789STDY5834889,bacterium LF-3
43,48,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [13]:
microbes.shape

(45, 1980)

### Step 5: Check for Duplicate Rows

In [14]:
microbes.duplicated().sum()

0

In [15]:
microbes["subject"].duplicated().sum()

0

### Step 6: Validate Binary Microbiome Values

In [16]:
microbe_cols = microbes.columns.drop("subject")

invalid_values = {}

for col in microbe_cols:
    invalid = microbes.loc[
        ~microbes[col].isin([0, 1]) & microbes[col].notna(),
        col
    ]

    if len(invalid) > 0:
        invalid_values[col] = invalid.unique()

print(invalid_values)

{}

### Step 7: Check Subject IDs and Unique Subjects

In [17]:
print("Unique subjects:", microbes["subject"].nunique())
print("Total rows:", len(microbes))
print("Duplicate subject IDs:", microbes["subject"].duplicated().sum())

Unique subjects: 45
Total rows: 45
Duplicate subject IDs: 0

In [80]:
sorted(microbes["subject"].unique())

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 38,
 39,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

### Step 8: Standardize Column Names

In [18]:
import re

microbes.columns = (
    microbes.columns
    .str.strip()                           # remove leading/trailing spaces
    .str.lower()                           # convert to lowercase
    .str.replace(r"[^\w\s]", "", regex=True)   # remove special characters
    .str.replace(r"\s+", "_", regex=True)      # replace spaces with underscore
    .str.replace(r"_+", "_", regex=True)       # replace multiple underscores with one
    .str.strip("_")                        # remove leading/trailing underscores
)

In [19]:
microbes.columns[:20].tolist()

['subject',
 'abiotrophia_defectiva',
 'abiotrophia_sp_hmsc24b09',
 'acetivibrio_ethanolgignens',
 'acetivibrio_ethanolgignens_strain_acet33324',
 'achromobacter',
 'acidaminococcus_intestini_rycmr95',
 'acidaminococcus_sp_bv3l6',
 'acidaminococcus_sp_d21',
 'acidaminococcus_sp_hpa0509',
 'acidovorax_sp_js42',
 'acidovorax_sp_na3',
 'acidovorax_sp_t1',
 'acinetobacter',
 'acinetobacter_johnsonii',
 'acinetobacter_towneri',
 'actinobaculum_sp_oral_taxon_183_str_f0552',
 'actinomyces',
 'actinomyces_cardiffensis_f0333',
 'actinomyces_dentalis_dsm_19115']

#### 8.1 Check for any duplicate column names

In [20]:
duplicate_columns = microbes.columns[microbes.columns.duplicated()].tolist()

print("Duplicate column names:", duplicate_columns)
print("Number of duplicate columns:", len(duplicate_columns))

Duplicate column names: ['ruminococcus_gnavus_atcc_29149']
Number of duplicate columns: 1

In [21]:
microbes.loc[:, microbes.columns == "ruminococcus_gnavus_atcc_29149"]

    ruminococcus_gnavus_atcc_29149  ruminococcus_gnavus_atcc_29149
0                                1                               0
1                                1                               0
2                                1                               0
3                                1                               0
4                                1                               0
5                                0                               0
6                                1                               0
7                                1                               0
8                                1                               0
9                                0                               0
10                               1                               0
11                               1                               0
12                               1                               0
13                               1                               0
14                               1                               0
15                               1                               0
16                               1                               0
17                               0                               0
18                               0                               0
19                               0                               1
20                               0                               1
21                               0                               0
22                               0                               0
23                               0                               0
24                               0                               0
25                               0                               1
26                               0                               1
27                               0                               0
28                               0                               0
29                               0                               0
30                               0                               1
31                               0                               1
32                               0                               1
33                               0                               0
34                               0                               0
35                               0                               0
36                               0                               1
37                               0                               1
38                               0                               1
39                               0                               0
40                               0                               1
41                               0                               0
42                               0                               1
43                            <NA>                            <NA>
44                               0                               1

#### 8.2 Changing the column name in order to retain it

In [22]:
cols = list(microbes.columns)

dup_name = "ruminococcus_gnavus_atcc_29149"

idx = [i for i, c in enumerate(cols) if c == dup_name]

cols[idx[0]] = "ruminococcus_gnavus_atcc_29149"
cols[idx[1]] = "ruminococcus_gnavus_atcc_29149_bracket"

microbes.columns = cols

In [23]:
microbes.columns.is_unique

True

In [24]:
[c for c in microbes.columns if "ruminococcus_gnavus_atcc_29149" in c]

['ruminococcus_gnavus_atcc_29149', 'ruminococcus_gnavus_atcc_29149_bracket']

In [25]:
microbes.shape

(45, 1980)

In [26]:
microbes_flipped = microbes.T
microbes_flipped

,0,1,2,3,4,5,6,7,8,9,...,35,36,37,38,39,40,41,42,43,44
subject,1,2,3,4,5,6,7,8,9,10,...,39,41,42,43,44,45,46,47,48,49
abiotrophia_defectiva,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,<NA>,0
abiotrophia_sp_hmsc24b09,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,<NA>,0
acetivibrio_ethanolgignens,1,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,<NA>,0
acetivibrio_ethanolgignens_strain_acet33324,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,<NA>,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ruminococcus_torques_strain_2789stdy5608833,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,<NA>,0
ruminococcus_torques_strain_2789stdy5608867,1,1,1,1,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,<NA>,0
ruminococcus_torques_strain_2789stdy5834841,1,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,<NA>,0
ruminococcus_torques_strain_2789stdy5834889,1,1,1,1,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,<NA>,0
bacterium_lf3,1,1,1,0,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,<NA>,0

In [27]:
microbes_long = microbes.melt(
    id_vars="subject",
    var_name="microorganism",
    value_name="presence"
)

microbes_long.head()

   subject          microorganism  presence
0        1  abiotrophia_defectiva         0
1        2  abiotrophia_defectiva         0
2        3  abiotrophia_defectiva         0
3        4  abiotrophia_defectiva         0
4        5  abiotrophia_defectiva         0

In [ ]:
microbes_long.shape

### Step 9: Final Data Quality Review

In [28]:
print("Final shape:", microbes.shape)
print("Total missing values:", microbes.isna().sum().sum())
print("Duplicate rows:", microbes.duplicated().sum())
print("Duplicate subjects:", microbes["subject"].duplicated().sum())
print("Column names unique:", microbes.columns.is_unique)

Final shape: (45, 1980)
Total missing values: 1979
Duplicate rows: 0
Duplicate subjects: 0
Column names unique: True

In [29]:
microbe_cols = microbes.columns.drop("subject")

valid_binary = microbes[microbe_cols].isin([0, 1])

print("All microbe values are binary:", valid_binary.all().all())

All microbe values are binary: False

### Step 10: Export Cleaned Microbes Data to CSV

In [30]:
microbes_long.to_csv(
    "DataMiners06_Microbes_LongFormat.csv",
    index=False
)

In [31]:
import os

print(
    "File exists:",
    os.path.exists("DataMiners06_Microbes_LongFormat.csv")
)

File exists: True

In [32]:
microbes_long.to_csv(
    r"C:\Users\karth\Downloads\DataMiners06_Microbes_LongFormat.csv",
    index=False
)

# Part 3 : Bio Cleaning

In [95]:
!pip install fg-data-profiling pandas numpy

Requirement already satisfied: fg-data-profiling in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (4.19.1)
Requirement already satisfied: pandas in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (1.26.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (1.15.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (3.7.2)
Requirement already satisfied: pydantic<3,>=2 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (3.1.6)
Requirement already satisfied: visions[type_image_path]<0.8.2,>=0.7.5 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (0.8.1)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (4.70.0)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from fg-data-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (1.8.0)
Requirement already satisfied: pillow in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from imagehash==4.3.2->fg-data-profiling) (10.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from jinja2<3.2,>=3.1.6->fg-data-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (4.41.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (23.1)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from matplotlib<=3.10,>=3.5->fg-data-profiling) (3.0.9)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from numba<0.63,>=0.60->fg-data-profiling) (0.45.1)
Requirement already satisfied: joblib>=0.14.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from phik<0.13,>=0.12.5->fg-data-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from pydantic<3,>=2->fg-data-profiling) (0.4.4)
Requirement already satisfied: six>=1.5 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (1.26.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from requests<3,>=2.32.0->fg-data-profiling) (2022.6.15)
Requirement already satisfied: patsy>=0.5.6 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from statsmodels<1,>=0.13.2->fg-data-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from tqdm<5,>=4.66.3->fg-data-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (3.4.2)
Requirement already satisfied: puremagic in c:\users\karth\appdata\local\programs\python\python310\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->fg-data-profiling) (1.30)

WARNING: visions 0.8.1 does not provide the extra 'type_image_path'

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: C:\Users\karth\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [96]:
# Importing required Libraries

import pandas as pd
import re
import numpy as np
import data_profiling
from data_profiling import ProfileReport

C:\Users\karth\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Load Bio Dataset

### Read Bio Data

In [97]:
# Read file 'bio.csv' and store it into df
import pandas as pd

bio = pd.read_csv(
    r"C:\Users\karth\Downloads\CGMacros_Datathon_Aug_2026\Datathon_Aug_2026\bio.csv"
)

bio.head()

,subject,Age,Gender,BMI,Body weight,Height,Self-identify,A1c PDL (Lab),Fasting GLU - PDL (Lab),Insulin,...,LDL (Cal),VLDL (Cal),Cho/HDL Ratio,Collection time PDL (Lab),#1 Contour Fingerstick GLU,Time (t),#2 Contour Fingerstick GLU,Time (t).1,#3 Contour Fingerstick GLU,Time (t).2
0,1,27,M,22.265239,133.8,65.0,Hispanic/Latino,5.4,91,2.5,...,130,13,2.9,11:06:00 AM,89,9:40,73,12:11,81,13:18
1,2,49,F,30.946742,169.2,62.0,Hispanic/Latino,5.5,93,14.8,...,78,12,2.0,7:38:00 AM,91,7:52,123,9:21,80,10:22
2,3,59,F,26.948690,157.0,64.0,Hispanic/Latino,6.5,118,17.4,...,90,31,2.6,7:25:00 AM,119,7:38,166,9:23,98,10:23
3,4,33,F,42.384279,262.6,66.0,Hispanic/Latino,5.5,105,19.4,...,164,60,5.8,7:20:00 AM,109,7:37,110,9:04,90,10:01
4,5,51,F,30.957534,172.0,62.5,Hispanic/Latino,6.6,144,12.9,...,157,78,7.1,7:45:00 AM,139,8:59,215,10:52,130,11:54

### Generate Data Profiling Report

In [98]:
from data_profiling import ProfileReport

profile = ProfileReport(
    bio,
    title="Bio Profiling Report",
    explorative=True
)

profile.to_file(
    r"C:\Users\karth\Downloads\Bio_Profiling_Report.html"
)

Summarize dataset:  62%|██████▏   | 18/29 [00:00<00:00, 102.71it/s, Describe variable: Time (t).2]
100%|██████████| 24/24 [00:00<00:00, 374.01it/s]<00:00, 102.71it/s, Describe variable: Time (t).2]
Summarize dataset: 100%|██████████| 357/357 [00:36<00:00,  9.69it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.99s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 28.44it/s]

In [99]:
import os

path = r"C:\Users\karth\Downloads\Bio_Profiling_Report.html"

print("File exists:", os.path.exists(path))

File exists: True

### Check Dataset Dimensions and Column Names

In [100]:
# Check the shape of the data and column names
bio.shape
print(bio.shape)
print(bio.columns.tolist())

(45, 24)
['subject', 'Age', 'Gender', 'BMI', 'Body weight ', 'Height ', 'Self-identify ', 'A1c PDL (Lab)', 'Fasting GLU - PDL (Lab)', 'Insulin ', 'Triglycerides', 'Cholesterol', 'HDL', 'Non HDL ', 'LDL (Cal)', 'VLDL (Cal)', 'Cho/HDL Ratio', 'Collection time PDL (Lab)', '#1 Contour Fingerstick GLU', 'Time (t)', ' #2 Contour Fingerstick GLU', 'Time (t).1', '#3 Contour Fingerstick GLU', 'Time (t).2']

### Inspect Data Types in Detail

In [101]:
# Check datatypes
bio.dtypes

# Checking data types in detail
for col in bio.columns:
    underlying_types = bio[col].apply(type).unique()
    sample_val = bio[col].dropna().iloc[0] if not bio[col].dropna().empty else "All NaN"
    print(f"Column: {col:<25} | Pandas Dtype: {str(bio[col].dtype):<10} | Actual Types: {str(underlying_types):<30} | Sample: {sample_val}")

Column: subject                   | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 1
Column: Age                       | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 27
Column: Gender                    | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: M
Column: BMI                       | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 22.26523858
Column: Body weight               | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 133.8
Column: Height                    | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 65.0
Column: Self-identify             | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: Hispanic/Latino
Column: A1c PDL (Lab)             | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 5.4
Column: Fasting GLU - PDL (Lab)   | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 91
Column: Insulin                   | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.5
Column: Triglycerides             | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 67
Column: Cholesterol               | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 216
Column: HDL                       | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 74
Column: Non HDL                   | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 142
Column: LDL (Cal)                 | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 130
Column: VLDL (Cal)                | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 13
Column: Cho/HDL Ratio             | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.9
Column: Collection time PDL (Lab) | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: 11:06:00 AM
Column: #1 Contour Fingerstick GLU | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 89
Column: Time (t)                  | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: 9:40
Column:  #2 Contour Fingerstick GLU | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 73
Column: Time (t).1                | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: 12:11
Column: #3 Contour Fingerstick GLU | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 81
Column: Time (t).2                | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: 13:18

### Check for Missing Values

In [102]:
# Check for null data
bio.isnull().sum()

subject                        0
Age                            0
Gender                         0
BMI                            0
Body weight                    0
Height                         0
Self-identify                  0
A1c PDL (Lab)                  0
Fasting GLU - PDL (Lab)        0
Insulin                        0
Triglycerides                  0
Cholesterol                    0
HDL                            0
Non HDL                        0
LDL (Cal)                      0
VLDL (Cal)                     0
Cho/HDL Ratio                  0
Collection time PDL (Lab)      0
#1 Contour Fingerstick GLU     0
Time (t)                       0
 #2 Contour Fingerstick GLU    0
Time (t).1                     0
#3 Contour Fingerstick GLU     0
Time (t).2                     0
dtype: int64

In [103]:
bio.head(10)

,subject,Age,Gender,BMI,Body weight,Height,Self-identify,A1c PDL (Lab),Fasting GLU - PDL (Lab),Insulin,...,LDL (Cal),VLDL (Cal),Cho/HDL Ratio,Collection time PDL (Lab),#1 Contour Fingerstick GLU,Time (t),#2 Contour Fingerstick GLU,Time (t).1,#3 Contour Fingerstick GLU,Time (t).2
0,1,27,M,22.265239,133.8,65.00,Hispanic/Latino,5.4,91,2.5,...,130,13,2.9,11:06:00 AM,89,9:40,73,12:11,81,13:18
1,2,49,F,30.946742,169.2,62.00,Hispanic/Latino,5.5,93,14.8,...,78,12,2.0,7:38:00 AM,91,7:52,123,9:21,80,10:22
2,3,59,F,26.948690,157.0,64.00,Hispanic/Latino,6.5,118,17.4,...,90,31,2.6,7:25:00 AM,119,7:38,166,9:23,98,10:23
3,4,33,F,42.384279,262.6,66.00,Hispanic/Latino,5.5,105,19.4,...,164,60,5.8,7:20:00 AM,109,7:37,110,9:04,90,10:01
4,5,51,F,30.957534,172.0,62.50,Hispanic/Latino,6.6,144,12.9,...,157,78,7.1,7:45:00 AM,139,8:59,215,10:52,130,11:54
5,6,51,F,29.303451,197.0,68.75,White,5.2,96,6.4,...,118,15,2.8,7:45:00 AM,98,9:04,97,10:54,70,11:56
6,7,66,F,27.070327,199.6,72.00,Hispanic/Latino,5.9,108,15.9,...,67,18,3.0,8:00:00 AM,115,8:40,157,10:22,95,11:24
7,8,54,M,39.945440,218.4,62.00,Hispanic/Latino,5.8,112,17.7,...,95,29,3.0,8:55:00 AM,110,9:07,156,10:25,94,11:26
8,9,34,F,37.001506,183.2,59.00,Hispanic/Latino,5.7,122,25.7,...,108,62,5.1,7:32:00 AM,119,7:46,128,9:32,96,10:29
9,10,54,F,35.811892,195.8,62.00,Hispanic/Latino,5.7,100,15.3,...,110,20,3.3,7:44:00 AM,100,8:01,160,9:35,108,10:36

### Standardize Column Names

In [104]:
# Read and standardize column names
print(df.columns.tolist())
bio.columns =(
    bio.columns
    .str.strip()   # Remove spaces before and after column names
    .str.lower()   # Making everything lower case
    .str.replace('#', 'num_', regex=False)          # Replace # with a clean prefix
    .str.replace('/', '_per_', regex=False)         # Clarify ratios like Cho/HDL
    .str.replace(r'[\(\)]', '', regex=True)      # Strip out parentheses
    .str.replace(r'[^a-z0-9]', '_', regex=True)  #  Replace everything except letters/numbers with underscore
    .str.replace(r'[\s_]+', '_', regex=True)     # Collapse consecutive spaces/underscores into one
    .str.strip('_')
)

print(bio.columns.tolist())

['subject', 'source_file', 'Timestamp', 'Libre GL', 'Dexcom GL', 'HR', 'Calories (Activity)', 'METs', 'Meal Type', 'Calories', 'Carbs', 'Protein', 'Fat', 'Fiber', 'Amount Consumed', 'Image path']
['subject', 'age', 'gender', 'bmi', 'body_weight', 'height', 'self_identify', 'a1c_pdl_lab', 'fasting_glu_pdl_lab', 'insulin', 'triglycerides', 'cholesterol', 'hdl', 'non_hdl', 'ldl_cal', 'vldl_cal', 'cho_per_hdl_ratio', 'collection_time_pdl_lab', 'num_1_contour_fingerstick_glu', 'time_t', 'num_2_contour_fingerstick_glu', 'time_t_1', 'num_3_contour_fingerstick_glu', 'time_t_2']

### Detailed Missing Values Analysis

In [105]:
# Check the missing values
print(bio.isna().sum())

# Count cells containing only spaces in text columns
blank_spaces = bio.select_dtypes(include="object").apply(
    lambda col: col.astype("string").str.strip().eq("").sum()
)

print("\nBlank-space values:")
print(blank_spaces)

# Check the missing values in percentage
missing = bio.isnull().mean()*100
print(missing[missing>0].sort_values(ascending=False))

subject                          0
age                              0
gender                           0
bmi                              0
body_weight                      0
height                           0
self_identify                    0
a1c_pdl_lab                      0
fasting_glu_pdl_lab              0
insulin                          0
triglycerides                    0
cholesterol                      0
hdl                              0
non_hdl                          0
ldl_cal                          0
vldl_cal                         0
cho_per_hdl_ratio                0
collection_time_pdl_lab          0
num_1_contour_fingerstick_glu    0
time_t                           0
num_2_contour_fingerstick_glu    0
time_t_1                         0
num_3_contour_fingerstick_glu    0
time_t_2                         0
dtype: int64

Blank-space values:
gender                     0
self_identify              0
collection_time_pdl_lab    0
time_t                     0
time_t_1                   0
time_t_2                   0
dtype: int32
Series([], dtype: float64)

### Check For Duplicate Records

In [106]:
# check the duplicate records
n_dup = bio.duplicated().sum()
n_dup

0

In [107]:
# Checking Duplicates

bio[bio.duplicated(keep=False)].sort_values(by=list(bio.columns)).head(10)

Empty DataFrame
Columns: [subject, age, gender, bmi, body_weight, height, self_identify, a1c_pdl_lab, fasting_glu_pdl_lab, insulin, triglycerides, cholesterol, hdl, non_hdl, ldl_cal, vldl_cal, cho_per_hdl_ratio, collection_time_pdl_lab, num_1_contour_fingerstick_glu, time_t, num_2_contour_fingerstick_glu, time_t_1, num_3_contour_fingerstick_glu, time_t_2]
Index: []

[0 rows x 24 columns]

### Standardize Time Columns

In [108]:
time_cols = [
    "collection_time_pdl_lab",
    "time_t",
    "time_t_1",
    "time_t_2"
]

for col in time_cols:
    print(f"\n{col}:")
    print(bio[col].head(10).tolist())

collection_time_pdl_lab:
['11:06:00 AM', '7:38:00 AM', '7:25:00 AM', '7:20:00 AM', '7:45:00 AM', '7:45:00 AM', '8:00:00 AM', '8:55:00 AM', '7:32:00 AM', '7:44:00 AM']

time_t:
['9:40', '7:52', '7:38', '7:37', '8:59', '9:04', '8:40', '9:07', '7:46', '8:01']

time_t_1:
['12:11', '9:21', '9:23', '9:04', '10:52', '10:54', '10:22', '10:25', '9:32', '9:35']

time_t_2:
['13:18', '10:22', '10:23', '10:01', '11:54', '11:56', '11:24', '11:26', '10:29', '10:36']

In [109]:

# Convert the mixed strings into a standardized datetime object and extract just the time portion (HH:MM:SS)

bio['collection_time_pdl_lab'] = pd.to_datetime(bio['collection_time_pdl_lab'], errors='coerce').dt.time
bio['time_t'] = pd.to_datetime(bio['time_t'], errors='coerce').dt.time
bio['time_t_1'] = pd.to_datetime(bio['time_t_1'], errors='coerce').dt.time
bio['time_t_2'] = pd.to_datetime(bio['time_t_2'], errors='coerce').dt.time

print("Total rows:", len(bio))
print("Successfully converted:", bio["collection_time_pdl_lab"].notna().sum())
print("Failed timestamps:", bio["collection_time_pdl_lab"].isna().sum())

Total rows: 45
Successfully converted: 45
Failed timestamps: 0

C:\Users\karth\AppData\Local\Temp\ipykernel_23336\1137419285.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  bio['collection_time_pdl_lab'] = pd.to_datetime(bio['collection_time_pdl_lab'], errors='coerce').dt.time
C:\Users\karth\AppData\Local\Temp\ipykernel_23336\1137419285.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  bio['time_t'] = pd.to_datetime(bio['time_t'], errors='coerce').dt.time
C:\Users\karth\AppData\Local\Temp\ipykernel_23336\1137419285.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  bio['time_t_1'] = pd.to_datetime(bio['time_t_1'], errors='coerce').dt.time
C:\Users\karth\AppData\Local\Temp\ipykernel_23336\1137419285.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  bio['time_t_2'] = pd.to_datetime(bio['time_t_2'], errors='coerce').dt.time

In [110]:
bio.head()

,subject,age,gender,bmi,body_weight,height,self_identify,a1c_pdl_lab,fasting_glu_pdl_lab,insulin,...,ldl_cal,vldl_cal,cho_per_hdl_ratio,collection_time_pdl_lab,num_1_contour_fingerstick_glu,time_t,num_2_contour_fingerstick_glu,time_t_1,num_3_contour_fingerstick_glu,time_t_2
0,1,27,M,22.265239,133.8,65.0,Hispanic/Latino,5.4,91,2.5,...,130,13,2.9,11:06:00,89,09:40:00,73,12:11:00,81,13:18:00
1,2,49,F,30.946742,169.2,62.0,Hispanic/Latino,5.5,93,14.8,...,78,12,2.0,07:38:00,91,07:52:00,123,09:21:00,80,10:22:00
2,3,59,F,26.948690,157.0,64.0,Hispanic/Latino,6.5,118,17.4,...,90,31,2.6,07:25:00,119,07:38:00,166,09:23:00,98,10:23:00
3,4,33,F,42.384279,262.6,66.0,Hispanic/Latino,5.5,105,19.4,...,164,60,5.8,07:20:00,109,07:37:00,110,09:04:00,90,10:01:00
4,5,51,F,30.957534,172.0,62.5,Hispanic/Latino,6.6,144,12.9,...,157,78,7.1,07:45:00,139,08:59:00,215,10:52:00,130,11:54:00

### Analyze Numeric Values and Identify Outliers

In [111]:
# Check Numeric values and outliers
numeric_columns = [
    "age",
"bmi",
"body_weight",
"height",
"a1c_pdl_lab",
"fasting_glu_pdl_lab",
"insulin",
"triglycerides",
"cholesterol",
"hdl",
"non_hdl",
"ldl_cal",
"vldl_cal",
"cho_per_hdl_ratio",
"num_1_contour_fingerstick_glu",
"num_2_contour_fingerstick_glu",
"num_3_contour_fingerstick_glu"
]

numeric_summary = bio[numeric_columns].describe().T

numeric_summary[
    ["count", "mean", "std", "min", "25%", "50%", "75%", "max"]
]

,count,mean,std,min,25%,50%,75%,max
age,45.0,48.111111,12.703296,18.000000,40.000000,51.000000,58.000000,69.000000
bmi,45.0,31.149765,6.728244,20.689962,26.922934,30.038349,35.918461,49.088236
body_weight,45.0,182.502222,35.990090,116.800000,157.000000,180.000000,202.000000,284.600000
height,45.0,64.376667,3.277742,59.000000,62.000000,64.000000,67.000000,72.000000
a1c_pdl_lab,45.0,6.122222,0.908017,4.600000,5.500000,5.900000,6.900000,8.500000
fasting_glu_pdl_lab,45.0,120.688889,30.231548,79.000000,100.000000,109.000000,142.000000,218.000000
insulin,45.0,14.166667,8.263611,2.500000,9.300000,13.500000,17.800000,46.400000
triglycerides,45.0,160.022222,169.430797,40.000000,83.000000,121.000000,154.000000,1150.000000
cholesterol,45.0,191.644444,46.711959,91.000000,168.000000,187.000000,208.000000,345.000000
hdl,45.0,51.911111,15.428460,24.000000,42.000000,51.000000,60.000000,106.000000
non_hdl,45.0,139.733333,47.230768,38.000000,109.000000,137.000000,162.000000,283.000000
ldl_cal,45.0,128.955556,109.994412,21.000000,90.000000,115.000000,133.000000,800.000000
vldl_cal,45.0,35.777778,57.609536,8.000000,17.000000,24.000000,31.000000,400.000000
cho_per_hdl_ratio,45.0,12.655556,59.066771,1.700000,3.000000,3.800000,4.800000,400.000000
num_1_contour_fingerstick_glu,45.0,121.244444,29.339049,80.000000,100.000000,117.000000,139.000000,220.000000
num_2_contour_fingerstick_glu,45.0,160.711111,60.514695,73.000000,111.000000,157.000000,193.000000,314.000000
num_3_contour_fingerstick_glu,45.0,120.488889,46.660584,67.000000,92.000000,101.000000,131.000000,247.000000

### Identify Suspicious or Potential Error Values

In [112]:
# Checking suspicious or error values

suspicious_rows = bio[
    (bio["ldl_cal"] > 260 ) |
    (bio["vldl_cal"] > 78)
]

#print(suspicious_rows)
suspicious_rows[
    [
    "subject",
     "age",
"bmi",
"body_weight",
"height",
"a1c_pdl_lab",
"fasting_glu_pdl_lab",
"insulin",
"triglycerides",
"cholesterol",
"hdl",
"non_hdl",
"ldl_cal",
"vldl_cal",
"cho_per_hdl_ratio",
"num_1_contour_fingerstick_glu",
"num_2_contour_fingerstick_glu",
"num_3_contour_fingerstick_glu"
    ]
    ]

,subject,age,bmi,body_weight,height,a1c_pdl_lab,fasting_glu_pdl_lab,insulin,triglycerides,cholesterol,hdl,non_hdl,ldl_cal,vldl_cal,cho_per_hdl_ratio,num_1_contour_fingerstick_glu,num_2_contour_fingerstick_glu,num_3_contour_fingerstick_glu
11,12,52,30.272873,205.0,69.0,7.1,179,13.5,1150,213,24,189,800,400,400.0,186,279,215

### Standardize Ethnicity Values

In [113]:
# Changing text in self_identify column Black, African American

bio['self_identify'] = bio['self_identify'].replace('Black, African American', 'African American Black')

### Round BMI Values

In [114]:
# Rounding bmi column values

bio['bmi'] = np.ceil(bio['bmi'] * 100) / 100

### Replace Error Codes with Missing Values

In [115]:
# Replace the explicit error codes with NaN

bio.loc[bio["ldl_cal"] == 800, "ldl_cal"] = np.nan
bio.loc[bio["vldl_cal"] == 400, "vldl_cal"] = np.nan

### Rename and Format Columns

In [116]:
# Rename and clean formatting in one step
bio = bio.rename(columns={"self_identify": "ethnicity"})

In [117]:
for col in bio.columns:
    underlying_types = bio[col].apply(type).unique()
    sample_val = bio[col].dropna().iloc[0] if not bio[col].dropna().empty else "All NaN"
    print(f"Column: {col:<25} | Pandas Dtype: {str(bio[col].dtype):<10} | Actual Types: {str(underlying_types):<30} | Sample: {sample_val}")

Column: subject                   | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 1
Column: age                       | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 27
Column: gender                    | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: M
Column: bmi                       | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 22.27
Column: body_weight               | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 133.8
Column: height                    | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 65.0
Column: ethnicity                 | Pandas Dtype: object     | Actual Types: [<class 'str'>]                | Sample: Hispanic/Latino
Column: a1c_pdl_lab               | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 5.4
Column: fasting_glu_pdl_lab       | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 91
Column: insulin                   | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.5
Column: triglycerides             | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 67
Column: cholesterol               | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 216
Column: hdl                       | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 74
Column: non_hdl                   | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 142
Column: ldl_cal                   | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 130.0
Column: vldl_cal                  | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 13.0
Column: cho_per_hdl_ratio         | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.9
Column: collection_time_pdl_lab   | Pandas Dtype: object     | Actual Types: [<class 'datetime.time'>]      | Sample: 11:06:00
Column: num_1_contour_fingerstick_glu | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 89
Column: time_t                    | Pandas Dtype: object     | Actual Types: [<class 'datetime.time'>]      | Sample: 09:40:00
Column: num_2_contour_fingerstick_glu | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 73
Column: time_t_1                  | Pandas Dtype: object     | Actual Types: [<class 'datetime.time'>]      | Sample: 12:11:00
Column: num_3_contour_fingerstick_glu | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 81
Column: time_t_2                  | Pandas Dtype: object     | Actual Types: [<class 'datetime.time'>]      | Sample: 13:18:00

In [118]:
bio.head()

,subject,age,gender,bmi,body_weight,height,ethnicity,a1c_pdl_lab,fasting_glu_pdl_lab,insulin,...,ldl_cal,vldl_cal,cho_per_hdl_ratio,collection_time_pdl_lab,num_1_contour_fingerstick_glu,time_t,num_2_contour_fingerstick_glu,time_t_1,num_3_contour_fingerstick_glu,time_t_2
0,1,27,M,22.27,133.8,65.0,Hispanic/Latino,5.4,91,2.5,...,130.0,13.0,2.9,11:06:00,89,09:40:00,73,12:11:00,81,13:18:00
1,2,49,F,30.95,169.2,62.0,Hispanic/Latino,5.5,93,14.8,...,78.0,12.0,2.0,07:38:00,91,07:52:00,123,09:21:00,80,10:22:00
2,3,59,F,26.95,157.0,64.0,Hispanic/Latino,6.5,118,17.4,...,90.0,31.0,2.6,07:25:00,119,07:38:00,166,09:23:00,98,10:23:00
3,4,33,F,42.39,262.6,66.0,Hispanic/Latino,5.5,105,19.4,...,164.0,60.0,5.8,07:20:00,109,07:37:00,110,09:04:00,90,10:01:00
4,5,51,F,30.96,172.0,62.5,Hispanic/Latino,6.6,144,12.9,...,157.0,78.0,7.1,07:45:00,139,08:59:00,215,10:52:00,130,11:54:00

In [119]:
bio.tail()

,subject,age,gender,bmi,body_weight,height,ethnicity,a1c_pdl_lab,fasting_glu_pdl_lab,insulin,...,ldl_cal,vldl_cal,cho_per_hdl_ratio,collection_time_pdl_lab,num_1_contour_fingerstick_glu,time_t,num_2_contour_fingerstick_glu,time_t_1,num_3_contour_fingerstick_glu,time_t_2
40,45,46,F,32.89,162.8,59.0,Hispanic/Latino,6.1,148,46.4,...,96.0,48.0,4.9,07:05:00,142,07:23:00,244,08:24:00,122,09:38:00
41,46,51,M,28.17,179.8,67.0,Hispanic/Latino,7.4,154,7.9,...,260.0,25.0,5.6,07:20:00,144,07:29:00,247,08:35:00,200,09:43:00
42,47,62,M,31.38,182.8,64.0,Hispanic/Latino,6.9,150,9.7,...,103.0,33.0,4.7,07:15:00,157,07:25:00,211,08:31:00,148,09:31:00
43,48,22,F,21.14,127.0,65.0,White,4.8,79,10.2,...,97.0,13.0,3.1,07:28:00,86,07:43:00,84,08:45:00,97,09:45:00
44,49,58,F,36.10,184.8,60.0,Hispanic/Latino,7.2,148,25.2,...,81.0,25.0,3.4,08:19:00,145,08:35:00,257,09:33:00,182,10:37:00

### Export Cleaned Bio Data to CSV

In [120]:
# Save the DataFrame as a CSV file on the Colab server
bio.to_csv(
    r"C:\Users\karth\Downloads\DataMiners06_Bio_CleanedData.csv",
    index=False
)

In [121]:
import os

path = r"C:\Users\karth\Downloads\DataMiners06_Bio_CleanedData.csv"

print("File exists:", os.path.exists(path))

File exists: True

# Part 4: Gut Health Test Cleaning

### Load Gut Health Test Dataset

In [147]:
# Uploading file

import pandas as pd

gut_health = pd.read_csv(
    r"C:\Users\karth\Downloads\CGMacros_Datathon_Aug_2026\Datathon_Aug_2026\gut_health_test.csv"
)

gut_health.head()

,subject,Gut Lining Health,LPS Biosynthesis Pathways,"Biofilm, Chemotaxis, and Virulence Pathways",TMA Production Pathways,Ammonia Production Pathways,Metabolic Fitness,Active Microbial Diversity,Butyrate Production Pathways,Flagellar Assembly Pathways,...,Inflammatory Activity,Gut Microbiome Health,Digestive Efficiency,Protein Fermentation,Gas Production,Methane Gas Production Pathways,Sulfide Gas Production Pathways,Oxalate Metabolism Pathways,Salt Stress Pathways,Microbiome-Induced Stress
0,1,2.0,2.0,1.0,2.0,1.0,3.0,2.0,3.0,2.0,...,2.0,3.0,1.0,1.0,2.0,3.0,1.0,1.0,3.0,2.0
1,2,1.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,3.0,2.0,1.0
2,3,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,1.0,2.0,3.0,2.0,1.0,3.0,2.0
3,4,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,...,2.0,1.0,2.0,1.0,3.0,3.0,3.0,1.0,2.0,2.0
4,5,1.0,1.0,2.0,3.0,1.0,2.0,1.0,2.0,2.0,...,1.0,1.0,2.0,2.0,3.0,3.0,2.0,2.0,2.0,2.0

### Generate Data Profiling Report

In [139]:
from data_profiling import ProfileReport

profile = ProfileReport(
    gut_health,
    title="Gut Health Profiling Report",
    explorative=True
)

profile.to_file(
    r"C:\Users\karth\Downloads\Gut_Health_Profiling_Report.html"
)

Summarize dataset:  43%|████▎     | 12/28 [00:00<00:00, 18.77it/s, Describe variable: Microbiome-Induced Stress]
100%|██████████| 23/23 [00:00<00:00, 320.04it/s]<00:00, 36.09it/s, Describe variable: Microbiome-Induced Stress]
Summarize dataset: 100%|██████████| 34/34 [00:02<00:00, 11.87it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.96s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 111.62it/s]

### Check Dataset Dimensions, Column Names and Data Types

In [148]:
# Check the shape of data and coloumn names
gut_health.shape
print(gut_health.shape)
print(gut_health.columns.tolist())
# Check datatypes
gut_health.dtypes

(47, 23)
['subject', 'Gut Lining Health', 'LPS Biosynthesis Pathways', 'Biofilm, Chemotaxis, and Virulence Pathways', 'TMA Production Pathways', 'Ammonia Production Pathways', 'Metabolic Fitness', 'Active Microbial Diversity', 'Butyrate Production Pathways', 'Flagellar Assembly Pathways', 'Putrescine Production Pathways', 'Uric Acid Production Pathways', 'Bile Acid Metabolism Pathways', 'Inflammatory Activity', 'Gut Microbiome Health', 'Digestive Efficiency', 'Protein Fermentation', 'Gas Production', 'Methane Gas Production Pathways', 'Sulfide Gas Production Pathways', 'Oxalate Metabolism Pathways', 'Salt Stress Pathways', 'Microbiome-Induced Stress']

subject                                          int64
Gut Lining Health                              float64
LPS Biosynthesis Pathways                      float64
Biofilm, Chemotaxis, and Virulence Pathways    float64
TMA Production Pathways                        float64
Ammonia Production Pathways                    float64
Metabolic Fitness                              float64
Active Microbial Diversity                     float64
Butyrate Production Pathways                   float64
Flagellar Assembly Pathways                    float64
Putrescine Production Pathways                 float64
Uric Acid Production Pathways                  float64
Bile Acid Metabolism Pathways                  float64
Inflammatory Activity                          float64
Gut Microbiome Health                          float64
Digestive Efficiency                           float64
Protein Fermentation                           float64
Gas Production                                 float64
Methane Gas Production Pathways                float64
Sulfide Gas Production Pathways                float64
Oxalate Metabolism Pathways                    float64
Salt Stress Pathways                           float64
Microbiome-Induced Stress                      float64
dtype: object

In [149]:
# Check datatypes in detail
for col in gut_health.columns:
    underlying_types = gut_health[col].apply(type).unique()
    sample_val = gut_health[col].dropna().iloc[0] if not gut_health[col].dropna().empty else "All NaN"
    print(f"Column: {col:<48} | Pandas Dtype: {str(gut_health[col].dtype):<10} | Actual Types: {str(underlying_types):<30} | Sample: {sample_val}")

Column: subject                                          | Pandas Dtype: int64      | Actual Types: [<class 'int'>]                | Sample: 1
Column: Gut Lining Health                                | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: LPS Biosynthesis Pathways                        | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Biofilm, Chemotaxis, and Virulence Pathways      | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 1.0
Column: TMA Production Pathways                          | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Ammonia Production Pathways                      | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 1.0
Column: Metabolic Fitness                                | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 3.0
Column: Active Microbial Diversity                       | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Butyrate Production Pathways                     | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 3.0
Column: Flagellar Assembly Pathways                      | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Putrescine Production Pathways                   | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Uric Acid Production Pathways                    | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Bile Acid Metabolism Pathways                    | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 3.0
Column: Inflammatory Activity                            | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Gut Microbiome Health                            | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 3.0
Column: Digestive Efficiency                             | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 1.0
Column: Protein Fermentation                             | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 1.0
Column: Gas Production                                   | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0
Column: Methane Gas Production Pathways                  | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 3.0
Column: Sulfide Gas Production Pathways                  | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 1.0
Column: Oxalate Metabolism Pathways                      | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 1.0
Column: Salt Stress Pathways                             | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 3.0
Column: Microbiome-Induced Stress                        | Pandas Dtype: float64    | Actual Types: [<class 'float'>]              | Sample: 2.0

### Standardize Column Names

In [150]:
# Read and standardize column names
print(gut_health.columns.tolist())
gut_health.columns =(
    gut_health.columns
    .str.strip()   # Remove spaces before and after column names
    .str.lower()   # Making everything lower case
    .str.replace(', and', '_', regex=False)          # Replace "", and" with underscore
    .str.replace('#', 'num_', regex=False)          # Replace # with a clean prefix
    .str.replace('/', '_per_', regex=False)         # Clarify ratios like Cho/HDL
    .str.replace(r'[\(\)]', '', regex=True)      # Strip out parentheses
    .str.replace(r'[^a-z0-9]', '_', regex=True)  #  Replace everything except letters/numbers with underscore
    .str.replace(r'[\s_]+', '_', regex=True)     # Collapse consecutive spaces/underscores into one
    .str.strip('_')
)

print(gut_health.columns.tolist())

['subject', 'Gut Lining Health', 'LPS Biosynthesis Pathways', 'Biofilm, Chemotaxis, and Virulence Pathways', 'TMA Production Pathways', 'Ammonia Production Pathways', 'Metabolic Fitness', 'Active Microbial Diversity', 'Butyrate Production Pathways', 'Flagellar Assembly Pathways', 'Putrescine Production Pathways', 'Uric Acid Production Pathways', 'Bile Acid Metabolism Pathways', 'Inflammatory Activity', 'Gut Microbiome Health', 'Digestive Efficiency', 'Protein Fermentation', 'Gas Production', 'Methane Gas Production Pathways', 'Sulfide Gas Production Pathways', 'Oxalate Metabolism Pathways', 'Salt Stress Pathways', 'Microbiome-Induced Stress']
['subject', 'gut_lining_health', 'lps_biosynthesis_pathways', 'biofilm_chemotaxis_virulence_pathways', 'tma_production_pathways', 'ammonia_production_pathways', 'metabolic_fitness', 'active_microbial_diversity', 'butyrate_production_pathways', 'flagellar_assembly_pathways', 'putrescine_production_pathways', 'uric_acid_production_pathways', 'bile_acid_metabolism_pathways', 'inflammatory_activity', 'gut_microbiome_health', 'digestive_efficiency', 'protein_fermentation', 'gas_production', 'methane_gas_production_pathways', 'sulfide_gas_production_pathways', 'oxalate_metabolism_pathways', 'salt_stress_pathways', 'microbiome_induced_stress']

### Detailed Missing Value Analysis

In [151]:
# Check the missing values
print(gut_health.isna().sum())

# Count cells containing only spaces in text columns
blank_spaces = gut_health.select_dtypes(include="object").apply(
    lambda col: col.astype("string").str.strip().eq("").sum()
)

print("\nBlank-space values:")
print(blank_spaces)

# Check the missing values in percentage
missing = gut_health.isnull().mean()*100
print(missing[missing>0].sort_values(ascending=False))

subject                                  0
gut_lining_health                        5
lps_biosynthesis_pathways                5
biofilm_chemotaxis_virulence_pathways    5
tma_production_pathways                  5
ammonia_production_pathways              5
metabolic_fitness                        5
active_microbial_diversity               5
butyrate_production_pathways             5
flagellar_assembly_pathways              5
putrescine_production_pathways           5
uric_acid_production_pathways            5
bile_acid_metabolism_pathways            5
inflammatory_activity                    5
gut_microbiome_health                    5
digestive_efficiency                     5
protein_fermentation                     5
gas_production                           5
methane_gas_production_pathways          5
sulfide_gas_production_pathways          5
oxalate_metabolism_pathways              5
salt_stress_pathways                     5
microbiome_induced_stress                5
dtype: int64

Blank-space values:
Series([], dtype: float64)
gut_lining_health                        10.638298
lps_biosynthesis_pathways                10.638298
salt_stress_pathways                     10.638298
oxalate_metabolism_pathways              10.638298
sulfide_gas_production_pathways          10.638298
methane_gas_production_pathways          10.638298
gas_production                           10.638298
protein_fermentation                     10.638298
digestive_efficiency                     10.638298
gut_microbiome_health                    10.638298
inflammatory_activity                    10.638298
bile_acid_metabolism_pathways            10.638298
uric_acid_production_pathways            10.638298
putrescine_production_pathways           10.638298
flagellar_assembly_pathways              10.638298
butyrate_production_pathways             10.638298
active_microbial_diversity               10.638298
metabolic_fitness                        10.638298
ammonia_production_pathways              10.638298
tma_production_pathways                  10.638298
biofilm_chemotaxis_virulence_pathways    10.638298
microbiome_induced_stress                10.638298
dtype: float64

### Identify Subjects with Completely Missing Data

In [152]:
# Check which subject has all empty columns or no data
empty_subjects = gut_health[gut_health.drop(columns=["subject"]).isna().all(axis=1)][
    "subject"
]
print(empty_subjects.tolist())

[24, 25, 26, 28, 48]

### Remove Subjects 24,25 with Completely Missing Data

In [153]:
# Remove those subject
subjects_to_remove = [24, 25]

gut_health = gut_health[
    ~gut_health["subject"].isin(subjects_to_remove)
].copy()

gut_health.reset_index(drop=True, inplace=True)

### Retain the rows we need

In [154]:
import numpy as np

# Subjects to retain even though Gut Health data is unavailable
retain_subjects = [26, 28, 48]

# All Gut Health columns except subject
gut_cols = gut_health.columns.drop("subject")

# Set their Gut Health values to NaN
gut_health.loc[
    gut_health["subject"].isin(retain_subjects),
    gut_cols
] = np.nan

In [155]:
for subject in [26, 28, 48]:
    print(
        subject,
        "present:",
        subject in gut_health["subject"].values
    )

26 present: True
28 present: True
48 present: True

### Check for Duplicate Records

In [156]:
# check the duplicates records
n_dup = gut_health.duplicated().sum()
n_dup

0

### Analyze Numeric Values and Identify Outliers

In [157]:
# Check numeric columns for impossible values and outliers
numeric_columns = [
  "subject",
  "gut_lining_health",
  "lps_biosynthesis_pathways",
  "biofilm_chemotaxis_virulence_pathways",
  "tma_production_pathways",
  "ammonia_production_pathways",
  "metabolic_fitness",
  "active_microbial_diversity",
  "butyrate_production_pathways",
  "flagellar_assembly_pathways",
  "putrescine_production_pathways",
  "uric_acid_production_pathways",
  "bile_acid_metabolism_pathways",
  "inflammatory_activity",
  "gut_microbiome_health",
  "digestive_efficiency",
  "protein_fermentation",
  "gas_production",
  "methane_gas_production_pathways",
  "sulfide_gas_production_pathways",
  "oxalate_metabolism_pathways",
  "salt_stress_pathways",
  "microbiome_induced_stress"
]

numeric_summary = gut_health[numeric_columns].describe().T

numeric_summary[
    ["count", "mean", "std", "min", "25%", "50%", "75%", "max"]
]

,count,mean,std,min,25%,50%,75%,max
subject,45.0,24.422222,14.627945,1.0,12.00,23.0,36.00,49.0
gut_lining_health,42.0,1.857143,0.751305,1.0,1.00,2.0,2.00,3.0
lps_biosynthesis_pathways,42.0,1.595238,0.664777,1.0,1.00,1.5,2.00,3.0
biofilm_chemotaxis_virulence_pathways,42.0,1.690476,0.680319,1.0,1.00,2.0,2.00,3.0
tma_production_pathways,42.0,2.071429,0.777515,1.0,1.25,2.0,3.00,3.0
ammonia_production_pathways,42.0,2.119048,0.771517,1.0,2.00,2.0,3.00,3.0
metabolic_fitness,42.0,2.119048,0.739228,1.0,2.00,2.0,3.00,3.0
active_microbial_diversity,42.0,2.142857,0.566178,1.0,2.00,2.0,2.00,3.0
butyrate_production_pathways,42.0,2.119048,0.669997,1.0,2.00,2.0,3.00,3.0
flagellar_assembly_pathways,42.0,1.976190,0.643470,1.0,2.00,2.0,2.00,3.0
putrescine_production_pathways,42.0,1.928571,0.808276,1.0,1.00,2.0,3.00,3.0
uric_acid_production_pathways,42.0,2.119048,0.632547,1.0,2.00,2.0,2.75,3.0
bile_acid_metabolism_pathways,42.0,2.000000,0.698430,1.0,2.00,2.0,2.00,3.0
inflammatory_activity,42.0,1.904762,0.691747,1.0,1.00,2.0,2.00,3.0
gut_microbiome_health,42.0,1.904762,0.790478,1.0,1.00,2.0,2.75,3.0
digestive_efficiency,42.0,1.857143,0.683300,1.0,1.00,2.0,2.00,3.0
protein_fermentation,42.0,1.857143,0.718108,1.0,1.00,2.0,2.00,3.0
gas_production,42.0,1.976190,0.715272,1.0,1.25,2.0,2.00,3.0
methane_gas_production_pathways,42.0,2.190476,0.772645,1.0,2.00,2.0,3.00,3.0
sulfide_gas_production_pathways,42.0,1.761905,0.532345,1.0,1.00,2.0,2.00,3.0
oxalate_metabolism_pathways,42.0,1.738095,0.766987,1.0,1.00,2.0,2.00,3.0
salt_stress_pathways,42.0,2.380952,0.622833,1.0,2.00,2.0,3.00,3.0
microbiome_induced_stress,42.0,1.928571,0.676896,1.0,1.25,2.0,2.00,3.0

### Convert Numeric Columns to Integer Data Type

In [160]:
# Convert all numeric columns to integers
# Convert numeric Gut Health columns to nullable integers

numeric_cols = gut_health.select_dtypes(include="number").columns

gut_health[numeric_cols] = (
    gut_health[numeric_cols]
    .round()
    .astype("Int64")
)

In [161]:
gut_health.dtypes

subject                                  Int64
gut_lining_health                        Int64
lps_biosynthesis_pathways                Int64
biofilm_chemotaxis_virulence_pathways    Int64
tma_production_pathways                  Int64
ammonia_production_pathways              Int64
metabolic_fitness                        Int64
active_microbial_diversity               Int64
butyrate_production_pathways             Int64
flagellar_assembly_pathways              Int64
putrescine_production_pathways           Int64
uric_acid_production_pathways            Int64
bile_acid_metabolism_pathways            Int64
inflammatory_activity                    Int64
gut_microbiome_health                    Int64
digestive_efficiency                     Int64
protein_fermentation                     Int64
gas_production                           Int64
methane_gas_production_pathways          Int64
sulfide_gas_production_pathways          Int64
oxalate_metabolism_pathways              Int64
salt_stress_pathways                     Int64
microbiome_induced_stress                Int64
dtype: object

In [134]:
gut_health.head()

,subject,gut_lining_health,lps_biosynthesis_pathways,biofilm_chemotaxis_virulence_pathways,tma_production_pathways,ammonia_production_pathways,metabolic_fitness,active_microbial_diversity,butyrate_production_pathways,flagellar_assembly_pathways,...,inflammatory_activity,gut_microbiome_health,digestive_efficiency,protein_fermentation,gas_production,methane_gas_production_pathways,sulfide_gas_production_pathways,oxalate_metabolism_pathways,salt_stress_pathways,microbiome_induced_stress
0,1,2,2,1,2,1,3,2,3,2,...,2,3,1,1,2,3,1,1,3,2
1,2,1,1,1,2,2,2,2,1,2,...,2,2,1,1,1,1,1,3,2,1
2,3,2,1,1,2,1,2,2,2,2,...,2,2,2,1,2,3,2,1,3,2
3,4,1,1,1,1,2,1,2,2,1,...,2,1,2,1,3,3,3,1,2,2
4,5,1,1,2,3,1,2,1,2,2,...,1,1,2,2,3,3,2,2,2,2

In [162]:
gut_health.shape
print(gut_health.shape)

(45, 23)

### Export Cleaned Gut Health Data to CSV

In [164]:
# Save the DataFrame as a CSV file on the Colab server
gut_health.to_csv(
    r"C:\Users\karth\Downloads\DataMiners06_GutHealthTest_CleanedData.csv",
    index=False
)

print("Gut Health cleaned file exported successfully.")

Gut Health cleaned file exported successfully.

In [165]:
import os

path = r"C:\Users\karth\Downloads\DataMiners06_GutHealthTest_CleanedData.csv"

print("File exists:", os.path.exists(path))

File exists: True